src/modules/icmaa-cms/mixins/categoryExtras.ts, src/modules/icmaa-cms/package.json, src/modules/icmaa-meta/README.md, src/modules/icmaa-meta/helper/ConfigMutator.ts, src/modules/icmaa-meta/helper/index.ts, src/modules/icmaa-meta/index.ts, src/modules/icmaa-meta/package.json, src/modules/icmaa-meta/store/index.ts, src/modules/index.ts, src/themes/icmaa-imp/assets/manifest.json, src/themes/icmaa-imp/components/core/blocks/Header/MinimalHeader.vue, src/themes/icmaa-imp/head.ts, src/themes/icmaa-imp/layouts/Default.vue, src/themes/icmaa-imp/layouts/Minimal.vue, src/themes/icmaa-imp/resource/meta/head-de.ts, src/themes/icmaa-imp/resource/meta/head.ts, tsconfig.json
* Add new icmaa-meta module to:
* Add custom store for meta-data
* Load meta-data per store-view
* Add meta-tag inheritance
* Improve default category meta-tags to use the category-extras ones
* Add our theme-path to `ts-config.json` for better IntelliJ
=> #179885 Add icmaa-meta module with inheritance logic for meta-tags

src/modules/icmaa-cms/mixins/categoryExtras.ts, src/modules/icmaa-cms/store/category-extras/getters.ts, src/themes/icmaa-imp/components/core/blocks/ICMAA/CategoryExtras/Header.vue
* Prefetch category-extras data without VSF asyncData method to prevent bug with `routeStore.route`  in getters (https://github.com/DivanteLtd/vue-storefront/issues/3328)
=> Bugfix for icmaa-cms/category-extras fetch on category-page

src/modules/icmaa-catalog/README.md, src/modules/icmaa-catalog/store/category/actions.ts, src/modules/icmaa-catalog/store/category/getters.ts, src/modules/icmaa-cms/helpers/genericStateModule.ts, src/modules/icmaa-cms/store/generic/actions.ts, src/modules/icmaa-cms/store/generic/getters.ts, src/modules/icmaa-cms/store/generic/index.ts, src/modules/icmaa-cms/store/generic/mutation-types.ts, src/modules/icmaa-cms/store/generic/mutations.ts, src/modules/icmaa-cms/types/GenericState.ts, src/themes/icmaa-imp/components/core/Breadcrumbs.vue, src/themes/icmaa-imp/components/core/blocks/Advice/Advice.vue, src/themes/icmaa-imp/components/core/blocks/Category/Presets.vue, src/themes/icmaa-imp/components/core/blocks/CategoryExtras/LogoLine.vue, src/themes/icmaa-imp/components/core/blocks/CategoryExtras/LogoLineBlock.vue, src/themes/icmaa-imp/components/core/blocks/SidebarMenu/SidebarMenu.vue, src/themes/icmaa-imp/layouts/Default.vue, src/themes/icmaa-imp/pages/Category.vue, src/themes/icmaa-imp/pages/Product.vue, src/themes/icmaa-imp/tailwind.js
* Add breadcrumbs logic (hide root-category and better styling)
* Add bugix for spacing-bug in PDP breadcrumbs
* Category-Filter-Preset:
* Only show available presets and sort them
* Cluster presets
* Load presets from storyblok
* Add generic cms state module registration:
* Create a way to dynamically load stuff to state-management without adding a whole new module each time
* E.g.: Filter-Presets, we only need them on the PLP and don't want to write a module to only get the list content from the CMS
* Only show logo-line-block if items exist
* Load advice only if client and cookie not set
=> #188009 Product-List-View progress and other improvements

core/lib/search/adapter/api/elasticsearchQuery.js, src/modules/icmaa-category/store/actions.ts, src/search/adapter/api/elasticsearchQuery.ts, src/search/adapter/api/searchAdapter.ts, src/themes/icmaa-imp/components/core/ProductListingWidget.vue
* Maybe this is becoming a core feature – if the pull-request https://github.com/DivanteLtd/vue-storefront/pull/3834 is going to be approved
* Change queries of product-list-widget on homepage
=> Extend ElasticSearch-Adapter to allow `or` and `or-null` filters

src/themes/icmaa-imp/components/core/blocks/Header/ButtonIcon.vue
* Somehow caused by `v-if` in `ButtonIcon` component – so I changed it to `v-show` and it worked – I don't get the magic behind that
=> BUGFIX // `n.setAttribute is not a function` error in production

src/modules/icmaa-config/helpers/price.ts, src/modules/icmaa-config/index.ts, src/modules/icmaa-config/lib/intl.ts, src/modules/icmaa-config/package.json, src/themes/icmaa-imp/components/core/ProductTile.vue, src/themes/icmaa-imp/mixins/product/priceMixin.ts, src/themes/icmaa-imp/pages/Product.vue
* Include price rendering as method because filters aren't used on SSR
* Add IntlPolyfill support for NodeJS (DivanteLtd#3837, DivanteLtd#3836)
* We can undo this commit if the PR #3837 is merged
=> Bugfix // Add IntlPolyfill support for NodeJS

ecosystem.json
* The build will currently fail when running `yarn build; yarn start`
See: https://github.com/DivanteLtd/vue-storefront/pull/3851
* This change will fix it temporarilly until it is fixed
See: https://github.com/DivanteLtd/vue-storefront/issues/3981
=> Bugfix // PM2 and Typescript isn't working in production mode

package.json, src/themes/icmaa-imp/package.json, yarn.lock
The `yarn install` fails if multiple versions of Cypress.io are installed. Thats why we consolidated the versions of our Cypress.io Version for the theme and the one VueStorefront is using. I updated both top `4.1.0`.
=> Bugfix for multiple Cypress versions

src/modules/icmaa-catalog/store/category/actions.ts, src/themes/icmaa-imp/components/core/blocks/CategoryExtras/LogoLine.vue
* If we use `loadCategories` and items are not fulfill the filter, they… will land in not found storage array and won't be triggered again
* Therefore we are using a similar, own action without not-found population
=> Bugfix // Missing categories if logoline fetches them using `loadCategories`

src/themes/icmaa-imp/components/core/Modal.vue, src/themes/icmaa-imp/components/core/blocks/AsyncSidebar/AsyncSidebar.vue, src/themes/icmaa-imp/components/core/blocks/Wishlist/Wishlist.vue
* If you have a open sidebar or modal and use the history-back button of the browser, the modal will disappear but the body-scroll-lock won't be disabled
* The `popstate` window event is the solution for that – we integrated it into the modal and sidebar component
=> Bugfix // Sidebar/Modal body-scroll-lock and overlay vs. history-back button

src/modules/icmaa-category/components/core/ProductListingWidget.vue, src/modules/icmaa-category/helpers/index.ts, src/modules/icmaa-category/store/actions.ts, src/modules/icmaa-category/store/getters.ts, src/modules/icmaa-category/store/mutations.ts, src/modules/icmaa-category/types/CategoryState.ts, src/modules/icmaa-cms/data-resolver/Task.ts, src/modules/icmaa-config/helpers/hash.ts, src/themes/icmaa-imp/pages/Home.vue
@cewald Funktioniert schon mal grundlegend. Aber man kann nicht zwei Widgets mit der identischen Kategorie und unterschiedlicher DepartmentId integrieren. 
Auf der Startseite sollen 4 Produkte aus Kategorie "New" aus Department "Merch" und 4 aus Department "Steetwear" angezeigt werden.
=> Add department as filter to ProductListingWidget

core/modules/cart/test/unit/store/productActions.spec.ts, core/modules/cms/test/unit/createHierarchyLoadQuery.spec.ts, core/modules/cms/test/unit/createLoadingBlockQuery.spec.ts, core/modules/cms/test/unit/createPageLoadingQuery.spec.ts, core/modules/cms/test/unit/createSingleBlockQuery.spec.ts, core/modules/cms/test/unit/createSinglePageLoadQuery.spec.ts, package.json, src/modules/icmaa-catalog/store/category/actions/index.ts, src/modules/icmaa-recommendations/store/actions.ts, src/search/adapter/api-search-query/searchAdapter.ts, src/themes/icmaa-imp/components/core/ProductImage.vue, src/themes/icmaa-imp/components/core/ProductTile.vue, yarn.lock
* Update to latest branch of our custom `storefront-query-builder` fork
* Update `storefront-query-builder`object in unit tests
* #198208, #197808 Add new custom sorting to `icmaa-catalog` overwrites and `icmaa-recommendations` module
* #198215 Prevent `Cannot serve directory media/catalog/product/`exceptions
=> #198208 & #197808 Add more complex sort options

src/themes/icmaa-imp/mixins/product/optionsMixin.ts
* `findConfigurableChildAsync` now needs an SKU to find a matching child
=> Bugfix for missing product-options

core/modules/catalog/helpers/index.ts, src/themes/icmaa-imp/mixins/product/optionsMixin.ts
* Otherwise the `AddToCartSidebar` component won't work because it cant find a valid configurable option caused by unequal type values (string vs number)
* It is caused by the refactoring of `getConfigurationMatchLevel`: 168f220dc1ee6b1cb15a2d581412dcdf296e9454
* PR #272 had the same cause – but it thought to need to solve it by adding the SKU, but that wasn't actually the cause
=> Add correct type matching to `getConfigurationMatchLevel`

src/modules/icmaa-external-checkout/index.ts, src/modules/icmaa-external-checkout/pages/ExternalSuccess.vue, src/modules/icmaa-user/data-resolver/UserService.ts, src/modules/icmaa-user/store/actions.ts
* Load last-order by JWT-Order-ID-Token stored inside a cookie when user returns from external checkout
* Connected to https://github.com/icmaa/vue-storefront-api/pull/60 & https://github.com/icmaa/shop-impericon/pull/1056
=> #187376 Bugfix for GTM tracking

package.json, yarn.lock
After the update to `@babel/preset-env` `^7.8.6"` I faced the exception during the build on a plain machine:
```
ERROR in ./core/service-worker/index.js Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
```
I've found this issue mentioned in the latest commits of the `babel` plugin and upgraded to `7.9.0` as recommended: https://github.com/babel/babel/pull/11283 and https://github.com/nodejs/node/issues/32852
=> Bugfix for build exception in Node v13.13+

src/modules/icmaa-external-checkout/index.ts
Remove token cookies on logout or if you already logged-in in `icmaa-external-checkout`:
* If you go to the checkout as a logged-in user and you return to the PWA, the token-cookies will be set
* If you then again log yourself out, those cookies won't be deleted and therfore will log you in again on   the next reload
* So we delete them on logout or if you are already logged-in on session-start
=> #199473 Remove token cookies in `icmaa-external-checkout`

src/modules/icmaa-google-tag-manager/mixins/checkoutSuccessGtm.ts, src/modules/icmaa-google-tag-manager/store/index.ts
* Revert "#187376 Change key-names in DataLayer of `icmaa-google-tag-manager` (#307)"
* In order to have the same results as in magento we try map the datatypes and contents of the datalayer as same as in magento
=> #187376 Improve DataLayer of `icmaa-google-tag-manager`

src/modules/icmaa-external-checkout/helper/index.ts, src/modules/icmaa-user/index.ts, src/modules/icmaa-user/store/getters.ts
* Attach checkout-url tokens as query-string parameters using `query-string`
* Log user out and clear cart if there is no customer token in state after session-start
=> #199755 Improve session handling during external-checkout

src/themes/icmaa-imp/components/core/blocks/AsyncSidebar/AsyncSidebar.vue, src/themes/icmaa-imp/components/core/blocks/AsyncSidebar/Sidebar.vue, src/themes/icmaa-imp/components/core/blocks/AsyncSidebar/Submenu.vue, src/themes/icmaa-imp/components/core/blocks/Category/Sidebar.vue, src/themes/icmaa-imp/components/core/blocks/Header/ButtonAccount.vue, src/themes/icmaa-imp/components/core/blocks/SidebarMenu/SidebarMenu.vue, src/themes/icmaa-imp/pages/Category.vue, src/themes/icmaa-imp/store/ui.ts, src/themes/icmaa-imp/tailwind.js, src/themes/icmaa-imp/test/e2e/integration/Catalog/filter.spec.ts
* Show check-icons if a filter is selected
* Show content behind sidebar in mobile view
* Fix header inside the sidebar
* Remove animation for submenus as they complicate the structure and don't bring benefits
=> #200014 Improve user-feedback in category filter sidebar

src/modules/icmaa-newsletter/routes.ts, src/themes/icmaa-imp/router/icmaa-cms/router.ts
* Put back the `/newsletter` landing-page to the theme as it anyway is a theme page and not functional bound to the `icmaa-newsletter` module
* This caused that all routes are overwritten by the `/:identifier` path and therefore are not accessible
=> #200281 Bugfix for wrong router names of `icmaa-newsletter`

src/modules/icmaa-category/store/actions.ts, src/modules/icmaa-user/store/actions.ts
* Don't set cluster for `always visible`/`0` as `customercluster` value
* Bugfix for sorting when clusters are used for products-list on homepage
=> #200709 Bugfix for `customercluster` related content

core/lib/sync/task.ts, src/modules/icmaa-advice/index.ts, src/modules/icmaa-category-extras/index.ts, src/modules/icmaa-cms/helpers/genericStateModule.ts, src/modules/icmaa-cms/index.ts, src/modules/icmaa-competitions/index.ts, src/modules/icmaa-config/index.ts, src/modules/icmaa-forms/index.ts, src/modules/icmaa-recommendations/index.ts, src/modules/icmaa-spotify/index.ts, src/modules/icmaa-teaser/index.ts, src/modules/icmaa-twitter/index.ts
* If we don't add a quota value, the localstorage could overflow and drop exceptions in browser - this should prevent this
=> Add localstorage quota to icmaa modules to enable garbage collection

src/modules/icmaa-cms/components/Wrapper.vue, src/modules/icmaa-recommendations/helpers/Rules.ts, src/themes/icmaa-imp/resource/i18n/it-IT.csv, src/themes/icmaa-imp/test/e2e/integration/Catalog/teaser.spec.ts, src/themes/icmaa-imp/test/e2e/integration/Customer/resetPassword.spec.ts
* #201742 Added E2E test for reset-password page (#343)
* #201739 Hide teaser on category-page when GET params are set (#349)
* #201936 Bugfix for transposed booleans in `icmaa-recommendations` module (#348)
* #200073 Change `liveyourmusic` to `impericon` (#350)
=> Release 2020-06-05

core/i18n/index.ts, core/lib/search/adapter/api-search-query/searchAdapter.ts, core/modules/catalog/helpers/associatedProducts/index.ts, core/modules/catalog/helpers/associatedProducts/setAttributesMetaFromProducts.ts, core/modules/catalog/helpers/associatedProducts/setBundleProducts.ts, core/modules/catalog/helpers/associatedProducts/setGroupedProduct.ts, core/modules/catalog/hooks/index.ts, core/modules/catalog/index.ts, src/modules/icmaa-catalog/store/category/actions/index.ts
* Update `loadCategoryProducts` & `loadMoreCategoryProducts` in `icmaa-catalog` module
* Disable child configuration in `loadCategoryProducts` and `loadMoreCategoryProducts` using `separateSelectedVariant` and remove custom deprecated `processCategoryProducts` overwrite
* Add `attributeMetadata` to response object of `api-search-query` search adapter to support `loadByAttributeMetadata` feature
* Load attributes data of attribute-meta for bundled and grouped products
* Remove warnings for `vue-i18n`
=> #199412 Enable meta-attribute support

core/modules/catalog/helpers/associatedProducts/buildQuery.ts, src/modules/icmaa-catalog/README.md, src/themes/icmaa-imp/components/core/blocks/AddToCartSidebar/BundleSelector.vue
* We commented out the stock-filter based on `listOutOfStockProducts` config value in `buildQuery` method of `core/modules/catalog/helpers/associatedProducts/buildQuery.ts` – otherwise a sold-out associated product wouldn't be visible in the selection sidebar and might cause an `property of undefined` error
=> Don't filter by stock when bundled children are loaded

src/modules/icmaa-cart/store/actions.ts
* When we put an item to cart using `cart/addItems()`, VSF does a stock check against Magento (if `config.stock.synchronize` is active). This check happens asynchrously using the `StockService.queueCheck()` method. The problem with that is that it sets the cart-items-hash on success and as the method is synchronous, this can lead into the problem that the `cart/sync` action can't see any changes by cart-items-hash if the success action (`cart/stockSync`) of the `queueCheck` is called with a small delay or you click really fast. Then there won't be any success messages shown to the customer as the `cart/sync` action returns nothing at the beginning because `cart/isSyncRequired` returns false. So if we call this synchronous, everything works fine.
=> #204161 Bugfix for missing user-feedback after adding product to cart (quickly)

src/themes/icmaa-imp/components/core/blocks/Product/ProductDetails.vue, src/themes/icmaa-imp/resource/i18n/de-DE.csv, src/themes/icmaa-imp/resource/i18n/en-US.csv
* Show important common phrase in description-tab on PDP
* They are configurable using an allow-list in configs: `icmaa_catalog.entities.product.importantCommonphrases`
Screenshot:
=> #204222 Show `commonphrases` in description-tab on PDP

src/themes/icmaa-imp/pages/Product.vue, src/themes/icmaa-imp/resource/i18n/cs-CZ.csv, src/themes/icmaa-imp/resource/i18n/de-DE.csv, src/themes/icmaa-imp/resource/i18n/en-US.csv, src/themes/icmaa-imp/resource/i18n/es-ES.csv, src/themes/icmaa-imp/resource/i18n/fi-FI.csv, src/themes/icmaa-imp/resource/i18n/fr-FR.csv, src/themes/icmaa-imp/resource/i18n/it-IT.csv, src/themes/icmaa-imp/resource/i18n/pl-PL.csv, src/themes/icmaa-imp/resource/i18n/pt-BR.csv, src/themes/icmaa-imp/resource/i18n/sv-SE.csv
* If a product is selected, but is out-of-stock (checked via API against Magento on select), show a message and make it possible to select another size
=> #204338 Show out-of-stock message after stock-check on PDP

core/lib/router-manager.ts, src/modules/icmaa-meta/helper/head/hreflang.ts, src/modules/icmaa-url/README.md, src/themes/icmaa-imp/router/index.ts
* Bugfix for `addRoutesByPriority` of `RouterManager`
* Sort custom `icmaa-imp` theme routes before default routes
* Remove trailing slash from root url in `hreflang`
=> #205748 Improve url- and route-handling

src/modules/icmaa-config/helpers/fetchResponseHandler.ts, src/modules/icmaa-spotify/package.json, src/modules/icmaa-spotify/store/actions.ts, src/modules/icmaa-twitter/package.json, src/modules/icmaa-twitter/store/actions.ts, src/modules/icmaa-user/store/actions.ts, src/themes/icmaa-imp/components/core/blocks/Auth/FacebookLoginButton.vue, src/themes/icmaa-imp/components/core/blocks/Twitter/TwitterStatusFeed.vue, yarn.lock
* `axios` has a 300kb+ package-size and we use only a small list of features so we switch to the `isomorphic-fetch` polyfill (8kb) which is already in use for all the other requests made in VSF
* As we use the `fetch` API we need to handle non-okay responses using a [small workaround](https://www.tjvantoll.com/2015/09/13/fetch-and-errors/) as `fetch` is handling responses to a specific standard
=> #207001 Reduce bundle-size by removing `axios`

src/modules/icmaa-config/index.ts
* We are settings some local-storage values to hide modals and stuff on initial load, these would be deleted again
=> #208829 Don't flush local-storage after new build when Cypress.io is running

src/themes/icmaa-imp/components/core/blocks/SearchPanel/SearchPanel.vue
* This way it splits all words correctly and keeps the special chars
=> Improve splitting reg-exp for search-aliases in search-panel

src/modules/icmaa-category-extras/mixins/categoryExtras.ts, src/modules/icmaa-category-extras/store/actions.ts
* Prevent loading category-extras on unload and/or without identifier
* The category watcher of the CLP mixin would call category-extras when route is left because of the changing (emptying) category state value
=> Bugfix for `icmaa-category-extras` module

core/modules/user/store/actions.ts, src/modules/icmaa-cart/store/actions.ts, src/themes/icmaa-imp/mixins/product/addtocartMixin.ts
* It's important to have `serverMergeByDefault` enabled to synchronize an existing customer cart but `serverSyncCanRemoveLocalItems` and `serverSyncCanModifyLocalItems` disabled. Only this way we prevent the `synchronizeServerItem` method during server- and client-cart-merge to remove the new item from cart again if the cart was empty at first. This is a misconception of the VSF.
=> #210379 Bugfix for add-to-cart routine and login to existing quote

src/themes/icmaa-imp/components/core/blocks/AsyncSidebar/Sidebar.vue, src/themes/icmaa-imp/components/core/blocks/SearchPanel/SearchPanel.vue
* Add better logic for empty/close routine of search-sidebar-panel
* Improve click-areas for buttons/inputs in search-sidebar
* Add an actual filter to search-results on category-filter buttons, instead of just search the first X results. This otherwise leads into the problem that items that aren't on the first result-page won't be able to filter for and no results are shown.
=> #210657 Improve search-sidebar

src/modules/icmaa-advice/index.ts, src/modules/icmaa-category-extras/index.ts, src/modules/icmaa-competitions/index.ts, src/modules/icmaa-config/index.ts, src/modules/icmaa-forms/index.ts, src/modules/icmaa-recommendations/index.ts, src/modules/icmaa-spotify/index.ts, src/modules/icmaa-teaser/index.ts, src/modules/icmaa-twitter/index.ts
* We currently called `init` in a scope where no "current" store can be assigned, thats why the storage mostly wasn't localized in our modules (these whose loaded initially)
* The flush of the local-storage after a new build only worked for the first called store-view, I made the `icmaa-config` storage localized so that the routine to check the build-time is store-based as well
=> Improve implementation of `storage-manager`

src/themes/icmaa-imp/components/core/blocks/Header/LanguageSwitcher.vue, src/themes/icmaa-imp/components/core/blocks/SidebarMenu/SidebarMenu.vue, src/themes/icmaa-imp/mixins/flagMixin.ts
* `/en` uses the EU flag as icon – this can't be found by store-code
=> Bugfix for missing country-flag in `/en`

src/themes/icmaa-imp/pages/Home.vue
* This is to redirect old urls to the VSF and open specific modals or sidebars like `login`, `register` or `cart`
=> Add url-params to home to open sidebars/modals by url

core/data-resolver/CategoryService.ts, core/data-resolver/types/DataResolver.d.ts, core/modules/catalog-next/store/category/getters.ts, src/modules/icmaa-catalog/components/Product.ts, src/modules/icmaa-category-extras/README.md, src/modules/icmaa-category-extras/helpers/index.ts, src/modules/icmaa-category-extras/store/actions.ts, src/modules/icmaa-category-extras/store/getters.ts, src/modules/icmaa-category-extras/store/index.ts, src/modules/icmaa-category-extras/store/mutations.ts, src/modules/icmaa-category-extras/types/CategoryExtrasState.ts, src/themes/icmaa-imp/components/core/ProductImage.vue, src/themes/icmaa-imp/components/core/blocks/CategoryExtras/LogoLine.vue
As we weren't able to connect an account/department of with a category, it was hard to fetch the category-extra information of a product. We now have an `account` attribute attached to the category-extras which simplifies the logic of fetching category-extras data for product.
Changes:
* Replace `childCategoryIdMap` state routine by "fetch-by-account-id"
* Add new logoline logic, based on path search instead of parent-id map
* Add complex sort options to `CategoryService` class to be able to add a sorting in `storefront-query-builder` style
* Improve `getCategoryByParams` as it will return the first value of `state.categoriesMap` if no route-params are set
* Bugfix for `ProductImage` component
=> #211292 Refactor how department/account related content is fetched

core/i18n/resource/i18n/en-US.csv, core/i18n/resource/i18n/it-IT.csv, src/modules/icmaa-catalog/store/category/actions/index.ts, src/modules/icmaa-catalog/store/product/actions.ts, src/modules/icmaa-category-extras/store/actions.ts, src/modules/icmaa-category-extras/store/getters.ts, src/themes/icmaa-imp/components/core/blocks/CategoryExtras/Header.vue, src/themes/icmaa-imp/components/core/blocks/Picture.vue, src/themes/icmaa-imp/pages/Category.vue, src/themes/icmaa-imp/pages/Product.vue, src/themes/icmaa-imp/resource/i18n/en-US.csv
* Bugfix for missing category-extras on PDP (category was overwritten by `product/loadProductBreadcrumbs`)
* Load category-header using the `picture` component and add preloading
=> Improve category-extras and -banner on PDP and CLP

src/modules/icmaa-catalog/store/category/actions/index.ts, src/modules/icmaa-catalog/store/product/actions.ts, src/themes/icmaa-imp/components/core/blocks/CategoryExtras/Header.vue, src/themes/icmaa-imp/mixins/lozadMixin.ts
* Load breadcrumbs more efficiently and only if needed
* Always load `@2x` variant as category-header image
* Add custom `MutationObserver` to `lozadMixin`
* We can't just use native `enableAutoReload` option because this calls the original `load` method inside its event observer. So we need to add our own observer code and load it using our method
=> Improve loading of category-extras and breadcrumbs

src/modules/icmaa-category/helpers/index.ts, src/themes/icmaa-imp/components/core/blocks/AddToCartSidebar/AddToCartSidebar.vue, src/themes/icmaa-imp/components/core/blocks/Auth/Register.vue, src/themes/icmaa-imp/components/core/blocks/ICMAA/Cms/Pages/Festival.vue, src/themes/icmaa-imp/resource/i18n/en-US.csv
* Wrong links in register popup
* Close sidebar/popup on `router-link` click
* Add `en-US` translation
* Lazyload images on `/festival` page
* Improve sorting in category-list
=> Small CMS bugfixes and translations

src/themes/icmaa-imp/components/core/blocks/SearchPanel/SearchPanel.vue
* This is a workaround as Android-Chrome won't recognize changes on inputs v-model until space or enter is pressed. It's connected to the used keyboard (Gboard and others) which uses composition (e.g. underlining and autocomplete). It is considered incomplete until you either hit space (indicating ending the word) or explicitly selecting a suggestion.
Source: https://github.com/vuejs/vue/issues/9777#issuecomment-478831263 & https://forum.vuejs.org/t/v-model-not-working-on-chrome-browser-on-android-device/36364
* Add `autocorrect="off"` & `autocomplete="off"` to search input
=> #212288 Bugfix for `v-model` in `SearchPanel` and Android keyboard

src/modules/icmaa-external-checkout/pages/ExternalSuccess.vue
* Otherwise the old cart could remain if the `onLogin` action takes long or fails
=> Clear cart first in `/order-success` page

core/modules/cart/store/actions/itemActions.ts, core/modules/cart/store/mutations.ts, core/modules/cart/test/unit/store/itemActions.spec.ts, src/modules/icmaa-google-tag-manager/README.md, src/modules/icmaa-google-tag-manager/hooks/afterRegistration.ts
* We added the `forceServerSilence` parameter to the `CART_ADD_ITEM`/`CART_DEL_ITEM` mutations and `cart/addItems`/`cart/removeItem` actions to know when it is an user-interaction and when not
=> Only call GTM `icmaa-*` mutation-events when they are not silenced

src/modules/icmaa-cart/store/actions.ts, src/modules/icmaa-user/store/actions.ts
* Otherwise the old (same) quote will be merged with the new quote which is merged during login in external checkout. This would otherwise look like the product is added to cart twice.
* Also add `{ sync = true }` parameter to `cart/removeCoupon` action (as we had overwritten the original action).
=> #213839 Clear cart before login when coming back from external-checkout

src/modules/icmaa-google-tag-manager/hooks/afterRegistration.ts, src/modules/icmaa-google-tag-manager/mixins/checkoutSuccessGtm.ts
* #214280 Add GTM event for spawn of notifications
* Load attribute-values (instead just ids) in datalayer on `/order-success` page
=> #214280 Add new GTM events

core/modules/cart/store/actions/itemActions.ts, core/modules/cart/store/mutations.ts, core/modules/cart/test/unit/store/itemActions.spec.ts, src/modules/icmaa-external-checkout/pages/ExternalSuccess.vue, src/modules/icmaa-google-tag-manager/hooks/afterRegistration.ts, src/modules/icmaa-google-tag-manager/hooks/index.ts, src/themes/icmaa-imp/components/core/blocks/Microcart/Product.vue
* We used to check `forceServerSilence` while we traced any commit for this action but there are some `sync/merge` actions that are using this action as well and therefore also will trigger the GTM event.
* Now we just track the click on the button in the cart and need to consider to re-trigger it when we add more ways to remove items from cart.
* We also undone our changes on the `cart/removeItem` action and the `CART_DEL_ITEM` commit method from the recent changes (dce7d672c2b08f8f4b7eaea0a389e6ce5690b972).
=> #214664 Create custom event-hook for `icmaa-remove-from-cart`

core/modules/cart/store/actions/mergeActions.ts, core/modules/cart/store/actions/synchronizeActions.ts, src/modules/icmaa-cart/store/actions.ts, src/modules/icmaa-external-checkout/index.ts, src/modules/icmaa-user/store/actions.ts
This behavior is caused by multiple problems:
* We didn't clear the cart before we reassign the session – this leads into a merge of the same cart into the existing one after the generic login in the VSF. I also disabled the `sync` parameter for the `cart/clear` action in `user/startSessionWithToken` as we don't need it and it might ends in conflicts with congruent requests.
* I removed the `vsf_token_quote ` cookie logic as we don't need this anymore. The user is logged in if the  `vsf_token_customer` cookie is set and will load the quote after login.
* Prevent a `TypeError: result.forEach is not a function` error notification on add-to-cart actions when the request returns an error. This was caused by a custom `cartHooks.beforeSync` hook and its `cart/updateFreeCartItems` action which …
=> #214316 Bugfix for wrong cart qty after coming back from external-checkout

.github/workflows/build.yml, .github/workflows/tests.yml
* There was an update in GitHub-Actions which needs us to change some things: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> Update Github actions

core/data-resolver/UserService.ts, core/data-resolver/types/DataResolver.d.ts, core/lib/sync/task.ts, core/modules/cart/store/actions/connectActions.ts, core/modules/cart/store/actions/synchronizeActions.ts, core/modules/user/store/actions.ts, src/modules/icmaa-cart/README.md, src/modules/icmaa-cart/helpers/index.ts, src/modules/icmaa-cart/helpers/notifications.ts, src/modules/icmaa-cart/store/actions.ts, src/modules/icmaa-cart/store/getters.ts, src/modules/icmaa-cart/store/index.ts, src/modules/icmaa-user/README.md, src/modules/icmaa-user/store/actions.ts, src/themes/icmaa-imp/components/core/blocks/Auth/Register.vue, src/themes/icmaa-imp/components/core/blocks/Microcart/Product.vue, src/themes/icmaa-imp/mixins/product/addtocartMixin.ts, src/themes/icmaa-imp/pages/MyAccount.vue
* Add support for new JWT expiration-time (we needed to overwrite a few core actions):
* I changed the `cart/getCurrentCartHash` getter as we don't need to create the cart-items-hash using the cart JWT anymore as this again is updated on each `cart/sync`. This would otherwise lead into a constant update of the cart because the `getCurrentCartHash` is changing. To be sure to check for the correct quote we added to quote-id into each product in the item payload of the Magento VSF bridge pull action.
* I refactored the `cart/sync` action to update the cart JWT on each `sync` action to extend the lifetime of the JWT or delete the current cart if it isn't valid anymore.
* I also refactored the `user/refreshUserProfile` action to update the customer JWT on each `me` action to extend the …
=> #214982 & #215028 Add JWT expiration-time and improve session-health

src/modules/icmaa-catalog/store/category/actions/index.ts, src/modules/icmaa-catalog/store/category/actions/search.ts, src/modules/icmaa-catalog/store/category/getters.ts, src/modules/icmaa-category-extras/store/getters.ts, src/modules/icmaa-category/store/actions.ts, src/modules/icmaa-cms/components/Wrapper.vue, src/modules/icmaa-recommendations/store/actions.ts, src/themes/icmaa-imp/components/core/blocks/Button.vue, src/themes/icmaa-imp/components/core/blocks/Microcart/Microcart.vue, src/themes/icmaa-imp/components/core/blocks/Notification/Notification.vue, src/themes/icmaa-imp/components/core/blocks/SearchPanel/SearchPanel.vue, src/themes/icmaa-imp/tailwind.js
* #214185 Show netto price in micro-carts shipping-totals if available
* #213838 Bugfix for long button-labels (especially in notifications)
* #214060 Bugfix for unisex product-images in `SearchPanel` component
* #214060 Bugfix for unisex product-images in recommendations and product-list-widget
* Put `configureChildProductsInCategoryList` config into `separateSelectedVariantInProductList` getter for better code
* #214166 Hide content-blocks in CLP when filter is selected
=> Multiple improvements

src/modules/icmaa-newsletter/data-resolver/NewsletterService.ts, src/modules/icmaa-user/data-resolver/UserService.ts, src/modules/icmaa-user/store/actions.ts
* The request `content-type`- and `accept`-header is by default marked as `application/json` for `Task.execute()` requests but must be explicitly set for `fetch` requests that aren't using the VSF task handler.
=> Hotfix for fetch-request payload

src/themes/icmaa-imp/components/core/blocks/CategoryExtras/Footer.vue
* Stripping and trimming of footer HTML might cause an exception on SSR load, caused by the HTML minifier
=> #216951 Bugfix for description in footer of CLP

src/themes/icmaa-imp/test/e2e/integration/Cms/home.spec.ts
* Sometimes there is a wrong logo in the logoline on homepage. If so the image can't be loaded and the test fails. I removed the image-check for the logos to prevent the tests getting flacky because of wrong CMS data.
=> Optimize E2E test for teaser on homepage

src/themes/icmaa-imp/components/core/blocks/CategoryExtras/Header.vue
* We cleaned up the data in Storyblok so we don't need to force `@2x` and replace the redundant `_mobile`
=> Update category-header implementation

src/themes/icmaa-imp/service-worker/index.js
We don't want to cache just all `/api/icmaa-*` requests as they probably needed to be updated in time.
I noticed that there are only a few that really needed to be cached besides the `/api/catalog` requests.
So I decided to make an allow-list for the cachable endpoints of the ICMAA modules.
=> #218052 Bugfix for service-worker rules for falsely cached API endpoints

core/i18n/intl.ts, src/modules/icmaa-config/helpers/price.ts, src/themes/icmaa-imp/mixins/product/addtocartMixin.ts
* This otherwise can cause an error in specific mobile Chrome versions (v88+) because it won't be able to load the missing language packages
* If we use old NodeJs versions (<=10) then there is loaded only a compact ICU package so we would need to load the missing packages using the polyfill (not tested as we usually using NodeJS version 13+)
=> #220254 Load `Intl` polyfill only on serverside requests

src/themes/icmaa-imp/components/core/Breadcrumbs.vue, src/themes/icmaa-imp/pages/Category.vue, src/themes/icmaa-imp/pages/Product.vue
=> #221741 Refactore breadcrumbs for mobile viewport

src/themes/icmaa-imp/pages/Category.vue
This feature was only visible at Phone and Deskop.
=> Bugfix // Add sub-categories and filter-preset in tablet-viewport

core/modules/user/index.ts, src/modules/icmaa-review/routes.ts, src/modules/icmaa-user/README.md, src/modules/icmaa-user/index.ts, src/modules/icmaa-user/store/actions.ts, src/modules/icmaa-user/store/index.ts, src/themes/icmaa-imp/components/core/blocks/AddToCartSidebar/AddToCartSidebar.vue, src/themes/icmaa-imp/components/core/blocks/Checkout/OrderReview.vue, src/themes/icmaa-imp/components/core/blocks/Checkout/ThankYouPage.vue, src/themes/icmaa-imp/components/core/blocks/MyAccount/MyAddresses.vue, src/themes/icmaa-imp/components/core/blocks/MyAccount/Navigation.vue, src/themes/icmaa-imp/pages/Home.vue, src/themes/icmaa-imp/pages/MyAccount.vue, src/themes/icmaa-imp/pages/PageNotFound.vue, src/themes/icmaa-imp/router/index.ts
* At the moment this was solved by a check when the `MyAccount` SFC is mounted. But this can lead to a race-condition where you will be logged out because the authentication isn't done yet despited you are already logged in.
* I refactored the authorization process for secure routes to use a global `beforeEach` router-guard for all routes that have the `isSecure` meta-tag in their definition.
* Then I refactored the `user/startSession` action to set the `session_started` state value at its end – this way I can create a state-watcher during the router-guard and redirect to the login page if the user isn't logged-in or the authorization times-out.
* I also needed to comment the original dispatch of `user/startSession` during the module-initialization and call it during the …
=> #222643 Refactor authentication for `/my-account` routes

.github/workflows/tests.yml, core/i18n/index.ts, core/lib/multistore/index.ts, src/modules/icmaa-config/store/getters.ts, src/modules/icmaa-meta/mixins/productMeta.ts, src/themes/icmaa-imp/index.js, src/themes/icmaa-imp/test/e2e/integration/Menu/main.spec.ts
* #222918 Bugfix for stateful-singletons in `currentStoreView()`
* This is related to `[dispatcher] Route not found de-fi-category null` errors and `storeCode of undefined` exceptions
* See issue: vuestorefront#5639 for more detailed information
* Add a store-config fallback to`icmaaConfig/getCurrentStoreConfig` getter for `metaInfo` calls on initial-state
* Update Github-Actions to use new `yarn install` and support master branch
* Drop an error if `loadLanguageAsync` fails
* Rename `once` event in `icmaa-imp` theme entrypoint
* Improve flacky E2E test for main-navigation
=> #222918 Hotfix for stateful-singletons in `currentStoreView()` and more

core/modules/catalog-next/hooks.ts, src/themes/icmaa-imp/pages/Category.vue, src/themes/icmaa-imp/pages/Product.vue
* As we removed the key from the main view mount-point to increase rendering-performance, the `mounted` method is only called once when the SFC is mounted and not when its updated. For example: a movement between two products doesn't rerender or mount the product SFC, it just updates its data. So I needed to ad a watcher for the current data on CLP and PDP.
* Add correct generic type to `catalog-next/productPageVisitedHook`
=> #223922 Bugfix for `icmaa-google-tag-manager` page-view hook

.github/workflows/tests.yml, core/modules/catalog-next/hooks.ts, src/modules/icmaa-external-checkout/pages/Success.vue, src/themes/icmaa-imp/components/core/blocks/Reviews/Reviews.vue, src/themes/icmaa-imp/pages/Category.vue, src/themes/icmaa-imp/pages/Product.vue, src/themes/icmaa-imp/resource/i18n/de-DE.csv, src/themes/icmaa-imp/resource/i18n/en-US.csv, src/themes/icmaa-imp/test/e2e/integration/Catalog/price.spec.ts, src/themes/icmaa-imp/test/e2e/support/commands.ts, src/themes/icmaa-imp/test/e2e/typings/index.d.ts
* #223921 Add `noindex, nofollow` to `/order-success` page (#584)
* #223922 Bugfix for `icmaa-google-tag-manager` page-view hook when moving between the same SFC (#585)
* #223087 Bugfix for missing reviews on PDP (#586)
* Add `group` and correct `build-id` to Github-Actions E2E tests (#588)
=> Release 2021-03-15

src/modules/icmaa-cdn/README.md, src/modules/icmaa-cdn/index.ts, src/modules/icmaa-cdn/types/HookTypes.ts, src/themes/icmaa-imp/components/core/ProductImage.vue, src/themes/icmaa-imp/components/core/blocks/CategoryExtras/Header.vue, src/themes/icmaa-imp/components/core/blocks/Picture.vue, src/themes/icmaa-imp/components/core/blocks/RetinaImage.vue, src/themes/icmaa-imp/components/core/blocks/Teaser/TeaserFullsize.vue
* The VSF module registration is synchronous and our `icmaa-cdn` module used a dynamic-import to register custom CDN providers during registration. This could lead into the problem that the `afterProductThumbnailPathGenerate` hook is not yet set when `getThumbnail` is called and will deliver wrong image paths.
=> #224741 Bugfix for race-condition during registration of `icmaa-cdn`

src/themes/icmaa-imp/components/core/blocks/Category/PromoBanner.vue
* When the product had an promo-id the field isn't `null` or `false`, it's just an empty string and we need to consider that
=> #224199 Bugfix for wrong promo-banner in CLP

src/modules/icmaa-google-tag-manager/store/index.ts, src/themes/icmaa-imp/components/core/blocks/Footer/Newsletter.vue
- add Breadcrumb-Data to these events `icmaa-product-view` and `icmaa-categroy-view`
- after the Release I will create the structured Data Tag via GTM
=> Add Breacrumb-Data to Datalayer

src/modules/robots/robots.txt
Google indexed automatically this urls.
_Indexiert, nicht in Sitemap gesendet_
`/p/:parentSku/:slug` - https://www.impericon.com/de/p/AH2008-010/nike-legasee-jdi-blackwhite-leggings/G395305_RED
`/c/:slug` - https://www.impericon.com/pt/c/volcom
=> #222888 Ignore `*/p/*` and `*/c/*` routes in `robots.txt`

core/modules/cart/helpers/syncCartWhenLocalStorageChange.ts, src/themes/icmaa-imp/components/core/blocks/Header/ButtonCart.vue
* Related PR of base-repository vuestorefront/vue-storefront#4083
* I've also added a bugfix for multistore environment vuestorefront/vue-storefront#5711
=> #222842 Add `syncCartWhenLocalStorageChange` event to window to keep tabs in sync

core/modules/cart/helpers/syncCartWhenLocalStorageChange.ts, package.json, src/modules/icmaa-cms/mixins/LazyloadMixin.ts, src/modules/icmaa-config/helpers/cleanTimeout.ts, src/modules/icmaa-product-alert/mixins/productStockAlertMixin.ts, src/themes/icmaa-imp/components/core/LanguageSwitcher.vue, src/themes/icmaa-imp/components/core/ProductImage.vue, src/themes/icmaa-imp/components/core/blocks/AsyncSidebar/LoadingError.vue, src/themes/icmaa-imp/components/core/blocks/Auth/FacebookLoginButton.vue, src/themes/icmaa-imp/components/core/blocks/Footer/Footer.vue, src/themes/icmaa-imp/components/core/blocks/Picture.vue, src/themes/icmaa-imp/components/core/blocks/Product/ProductGallery.vue, src/themes/icmaa-imp/components/core/blocks/Reviews/Reviews.vue, src/themes/icmaa-imp/mixins/lozadMixin.ts, src/themes/icmaa-imp/pages/Product.vue
* Enhanced support for multistore mode
* Add `removeEventListener` to avoid JS memory-leaks
* Add `clearTimeout` to avoid JS memory-leaks
* Disconnect `IntersectionObserver` to avoid JS memory-leaks
* Call `$off` for Vue `$on` api-events to avoid JS memory-leaks
* Add correct `yarn` and `node` version to `package.json`
=> #222842 Bugfixes for several memory leaks and more

src/modules/icmaa-cms/helpers/index.ts, src/modules/icmaa-looks/components/Look.vue
* Bugfix for `icmaa-looks`: Image wont change on router change
* Bugfix for `getCurrentStoreCode` helper: load default store-code if it exists
=> Small bugfixes

src/modules/icmaa-cms/helpers/index.ts, src/modules/icmaa-looks/components/Look.vue, src/themes/icmaa-imp/components/core/blocks/ICMAA/Cms/Pages/ServiceWiderruf.vue
* #223907 Use localized target email-address in `ServiceWiderruf` SFC (#625)
* Small bugfixes (#626)
* Bugfix for `icmaa-looks` // Image wont change on router change
* Bugfix for `getCurrentStoreCode` helper: load default store-code if it exists
=> Release 2021-04-15

src/themes/icmaa-imp/mixins/lozadMixin.ts
* This happens when the component is destroyed before the observer is bound
=> Prevent exception with the `lozadObserver` on component destroy

src/themes/icmaa-imp/components/core/ProductTile.vue, src/themes/icmaa-imp/mixins/product/priceMixin.ts, src/themes/icmaa-imp/test/e2e/cypress.json
* #227567 Bugfix: Show correct from-price for configurable products in CLP (#633)
* #227567 Prevent exception for first call of `reduce` (#634)
=> Release 2021-04-28

src/modules/icmaa-catalog/components/Product.ts, src/modules/icmaa-category-extras/mixins/categoryExtras.ts, src/modules/icmaa-category/components/List/Letter.vue, src/modules/icmaa-google-tag-manager/store/index.ts, src/modules/icmaa-user/store/getters.ts, src/themes/icmaa-imp/components/core/blocks/AsyncSidebar/TopButton.vue, src/themes/icmaa-imp/components/core/blocks/Category/FilterPresets.vue, src/themes/icmaa-imp/components/core/blocks/Header/ButtonUiSidebar.vue, src/themes/icmaa-imp/components/core/blocks/Navigation/ClusterNavigation.vue, src/themes/icmaa-imp/components/core/blocks/Navigation/Item.vue, src/themes/icmaa-imp/components/core/blocks/Navigation/Sidebar.vue, src/themes/icmaa-imp/components/core/blocks/Navigation/SubNavigation.vue, src/themes/icmaa-imp/layouts/Default.vue, src/themes/icmaa-imp/pages/Category.vue, src/themes/icmaa-imp/pages/Product.vue, src/themes/icmaa-imp/store/ui.ts
* #228430 Bugfix for styling on CLP (#639)
* #226629 Add 2nd layer to main-navigation (#640)
* Don't make requests Spotify on SSR (#641)
* #224313 Improve GTM tracking (#638)
* Don't load stock-status on SSR on PDP (#642)
* Load FilterPresets only on CSR to increase PLP response-time (#643)
=> Release 2021-05-11 

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/build.yml, app-imp-prod.yaml
GAE has a bug where it will drop an error for the latest NodeJS LTS version as he thinks it's not a trusted one:
```
The Node.js binary could not be verified.
```
We could just change the version number in the package JSON to `14.16.x` but then the GAE standard environment won't work because they force you to always use the [latest major version](https://cloud.google.com/appengine/docs/standard/nodejs/runtime#nodejs_version). Thats why we need to monkey-patch the `package.json` in the production build step until it is solved.
=> Hotfix for GAE flex environment support of NodeJS 14.17 LTS

src/modules/icmaa-google-tag-manager/hooks/afterRegistration.ts, src/modules/icmaa-google-tag-manager/hooks/index.ts, src/modules/icmaa-google-tag-manager/index.ts, src/modules/icmaa-google-tag-manager/store/index.ts, src/themes/icmaa-imp/pages/PageNotFound.vue, src/themes/icmaa-imp/router/index.ts
* Add custom `page-not-found` page-type to GTM
* Remove `documentTitle` from data-layer
TCK-224313
=> #224313 Add page-type for 404-pages in `icmaa-google-tag-manager` module

src/modules/icmaa-competitions/pages/Competition.vue, src/themes/icmaa-imp/components/core/blocks/Link.vue
We obviously sometimes need links to external sites. To be able to have universal code undepending of the entered url-path, I've added a new wrapper component which checks if it's an external link and then uses a `<a>` or `<router-link>`.
TCK-227190
=> #227190 Add `universal-link` component to support external links

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/build.yml, app-imp-prod.yaml, package.json, src/modules/icmaa-cms/helpers/index.ts, src/modules/icmaa-competitions/pages/Competition.vue, src/modules/icmaa-google-tag-manager/hooks/afterRegistration.ts, src/modules/icmaa-google-tag-manager/hooks/index.ts, src/modules/icmaa-google-tag-manager/index.ts, src/modules/icmaa-google-tag-manager/store/index.ts, src/themes/icmaa-imp/components/core/blocks/Link.vue, src/themes/icmaa-imp/pages/PageNotFound.vue, src/themes/icmaa-imp/router/index.ts
* #229652 Wrong format for emails on CMS pages (#656)
* Hotfix for GAE flex environment support of NodeJS 14.17 LTS (#658, #662)
* #224313 Add page-type for 404-pages in icmaa-google-tag-manager module (#660)
* #227190 Add universal-link component to support external links (#661)
=> Release 2021-05-21

src/themes/icmaa-imp/components/core/blocks/Navigation/SubNavigation.vue
Custom Tiles with fallback to MainNavigation. Add Json like in `block-navigation-main`with the `tiles` Identifier.
```
tiles:
- children:
- width: full
children:
- name: Neu
route: "/home.html?sort=online%3Adesc"
icon: new_releases
backgroundColor: primary
- name: Sale
route: "/home.html?is_in_sale=true"
icon: local_offer
backgroundColor: sale
- children:
- width: full
children:
- name: Top Sellers
route: "/home.html?sort=ranking_shop_bestseller%3Adesc"
icon: flag
backgroundColor: base-dark
- name: Preorder
route: "/clothing.html?preorder_searchable=6373"
icon: date_range
backgroundColor: base-dark
```
TCK-226629
=> #226629 Add support for custom tiles in sub-navigation sidebar

src/themes/icmaa-imp/components/core/blocks/Category/PromoBanner.vue, src/themes/icmaa-imp/tailwind.js
We need a new color for the new second navigation layer. New is already defined and we can add it to TailwindCSS with its own namespace.
TCK-226629
=>  #226629 Add new color-code for `new` and support TailwindCSS classes in promo-banner

src/themes/icmaa-imp/components/core/blocks/Navigation/SubNavigation.vue
The amount of blocks you would need to fill and change to show teaser isn't realistic (11 languages + 11 languages x 8 submenus = 99 blocks).
TCK-226629
=> #226629 Remove teaser from subnavigation

src/themes/icmaa-imp/components/core/blocks/AsyncSidebar/LoadingSpinner.vue, src/themes/icmaa-imp/components/core/blocks/Category/Sidebar.vue, src/themes/icmaa-imp/components/core/blocks/Microcart/Microcart.vue, src/themes/icmaa-imp/components/core/blocks/Navigation/ClusterNavigation.vue, src/themes/icmaa-imp/components/core/blocks/Navigation/Sidebar.vue, src/themes/icmaa-imp/components/core/blocks/Navigation/SubNavigation.vue, src/themes/icmaa-imp/components/core/blocks/Wishlist/Wishlist.vue, src/themes/icmaa-imp/store/ui.ts
* #231143 Add unified bottom padding to sidebars
* #231147 Bugfix for gender-switch on PLP
* Improve `LoadingSpinner` component and add it to `SubNavigation`
* Remove option for bold title in sub-navigation
TCK-231143
TCK-231147
TCK-226629
=> #226629 Improve 2nd navigation layer

src/modules/icmaa-google-tag-manager/store/index.ts
The image URL in Datalayer was only `/t/e/test.jpg`. Added a case for CatalogImages with `getThumbnailPath()`
URL is now `https://www.impericon.com/medai/catalog/product/t/e/test.jpg`
Because all structured-data is based on Datalayer were all wrong and generates tons of error in the search-console.
TCK-222888
=> #222888 - GTM - fix ImageURL

src/themes/icmaa-imp/components/core/blocks/ICMAA/Cms/Pages/Calendar.vue, src/themes/icmaa-imp/router/icmaa-cms/router.ts
- Add identifier for CSS class
- default without background-color
- changed routes for easter- und summer-calendar in Storyblok
TCK-234767
=> #234767 Consolidate calendar component

core/modules/cart/helpers/notifications.ts, src/modules/icmaa-checkout/routes.ts, src/modules/instant-checkout/components/InstantCheckout.vue, src/themes/icmaa-imp/components/core/blocks/Microcart/Microcart.vue, src/themes/icmaa-imp/mixins/product/addtocartMixin.ts
We should change this back once the checkout is fully migrated. But for now this will cause a conflict inside the first LB.
=> Change URL path of new checkout to prevent LB conflicts

src/modules/icmaa-checkout-com/components/methods/apm/Ideal.vue, src/modules/icmaa-checkout/components/Shipping.ts
* Add BIC select to iDeal payment-method
* Reset payment-method when saving shipping-method in checkout:
This is a bugfix for when an address changes but a address-specific payment-method is already selected. E.g. you select iDeal in NL and change your address to DE and wont be able to finish your order because of  "Payment method is not available" response of `setTotals` action.
TCK-233661
=> Hotfix // Improvements for `icmaa-checkout`

src/themes/icmaa-imp/components/core/blocks/Category/Sidebar.vue
* This is a bugfix to prevent missing filters if only one option is available for the current collection, but also hide specififc attributes if needed – like bands and brands.
This change needs a new config value `hideSingleOptionsFilters`:
https://github.com/icmaa/shop-workspace/commit/1d3e44a6999c049c2f6a03439f0797dfd060ffd1
TCK-225750
=> #225750 Add new `hideSingleOptionsFilters` option for filter-navigation on CLP

package.json, src/themes/icmaa-imp/components/core/CookieNotification.vue, src/themes/icmaa-imp/components/core/blocks/AsyncSidebar/AsyncSidebar.vue, src/themes/icmaa-imp/components/core/blocks/MyAccount/MyProductAlerts.vue, src/themes/icmaa-imp/layouts/Default.vue, src/themes/icmaa-imp/pages/Product.vue
* Bugfix for memory-leak on PDP 
* `beforeDestroy` and `destroyed` events aren't called on SSR and therefore won't unbind the callback
* Update start:inspect command to run without `ts-node`
* Don't load dynamic content on `created` hook
* This hooks would also be called on SSR and might cause unecessary memory and CPU usage
This PR should decrease the memory-usage under high load drastically.
TCK-239532
=> #239532 Improvements for SSR memory-leaks

src/modules/icmaa-catalog/helpers/defaultCategorySort.ts, src/modules/icmaa-catalog/store/category/actions/index.ts
* Use `getDefaultCategorySort` in `loadCategoryProducts` action to prevent unready `route.params` state property on client-side requests
TCK-243775
=> #243775 Bugfix for custom CLP sorting

src/modules/icmaa-cart/index.ts, src/modules/icmaa-cart/store/actions/couponActions.ts, src/themes/icmaa-imp/components/core/ProductTile.vue
* #245300 Remove incentives if a single item is deleted from cart
* Bugfix for add-to-cart of onesize products in CLP
* We need to replace the sku of cart-item by the SKU of the selected-variant to be able to check for it using `productsEquals` in `cart/mergeClientItem` action. Otherwise the product will be removed on reload or the next cart-action if you add an onesize product to cart from CLP.
TCK-245300
=> #245300 Bugfixes for add-to-cart /w incentives and on CLP

src/modules/icmaa-url/store/getters.ts, src/modules/icmaa-url/store/index.ts, src/themes/icmaa-imp/pages/Category.vue, src/themes/icmaa-imp/pages/SearchResult.vue
* Add check if prev-route was a category and add this feature to search-results page
TCK-221258
=> #221258 Improve browser-back on CLP

src/modules/icmaa-catalog/store/category/getters.ts
* This is to show filters in specific categories that normally only would be visible if a parent filter is selected, like `pants_type` and `pants_size` in `jeans.html` category.
TCK-248473
=> #248473 Add new category-option for CLP filters

src/modules/icmaa-google-tag-manager/components/jsonld/Product.vue
* Don't show `aggregateRating` if ratring-count is zero
* Show availability `out-of-stock` for configurable-products without child-products
TCK-248913
=> #248913 Bugfixes for structured-data on PDP

core/scripts/server.h3.ts, core/scripts/utils/cache-instance.js
* Add a `:` delimiter as suffix to FPC cache-prefix as desired in `ioredis` docs
* Add `cache-control` header for cached responses
* Add bugfix for invalidation by specific tags like `P-{ID}`
=> Improve full-page-cache and cache-control

core/scripts/server.h3.ts, src/modules/icmaa-cdn/server.h3.ts
* Add endpoint `/invalidate/cf/all` to force complete cache-bust of CloudFlare CDN cache
* Improve implementation of `h3` invalidation route, to make it extendable using server-hooks
* Add improved logging to track cache-invalidation events in logs
=> Add complete CF cache-bust and improve catch of JSON errors

src/modules/icmaa-cms/components/Wrapper.vue, src/themes/icmaa-imp/components/core/blocks/CategoryExtras/LinkList.vue, src/themes/icmaa-imp/pages/Home.vue
* We added a new component to the homepage for top-categories as test-links
* It's fetched from a Storyblok block called `home-top-categories` and its dependant on the selected gender
* This component is now also useable on landing-pages
TCK-249042
=> #249042 Add new link-list component to homepage and landing-pages

src/modules/icmaa-catalog/store/product/actions.ts
* If a product isn't configurable, due to missing children, the `setProductGallery` action isn't working and there also was an error inside the `if` clause for the `mergeConfigurableChildren` configuration in combination with unconfigured products.
TCK-250447
=> #250447 Bugfix for missing image on PDP

core/scripts/server.h3.ts
* Remove cache-control due to problems with caching in the frontend between stores
* Make `X-VS-Cache-Tags` header souvereign of enabled output-cache
TCK-250772
=> #250772 Remove cache-control due to problems

src/modules/icmaa-meta/mixins/categoryMeta.ts
* Use unified fields in category-response
* See https://github.com/icmaa/shop-workspace/pull/59 for config changes
TCK-250412
=> #250412 Improve category meta-titles and -descriptions

src/themes/icmaa-imp/pages/PageNotFound.vue
=> #251485 Add `404-*` cache-tag to 404 pages to be able to cache-bust by URL key

src/modules/icmaa-catalog/store/product/actions.ts, src/modules/icmaa-google-tag-manager/components/jsonld/Product.vue, src/themes/icmaa-imp/components/core/ProductTile.vue, src/themes/icmaa-imp/components/core/blocks/Checkout/AdditionalProducts/Product.vue, src/themes/icmaa-imp/components/core/blocks/Checkout/Cart/Product.vue, src/themes/icmaa-imp/components/core/blocks/Microcart/Product.vue, src/themes/icmaa-imp/components/core/blocks/Product/ProductGallery.vue, src/themes/icmaa-imp/components/core/blocks/Wishlist/Product.vue, src/themes/icmaa-imp/components/core/blocks/Wishlist/WishlistButton.vue
=> #252209 Use ´product.translatedName´ instead of `name` for translated product-titles

src/modules/icmaa-cms/helpers/index.ts, src/themes/icmaa-imp/webpack.config.js
* We don't need the whole Vue compiler in the client just to render some links into `<router-links>` inside HTML on client-side.
* I've refactored the `stringToComponent` method to replace the links inside of HTML based on the DOM and the `render` method of VueJS
TCK-250854
=> #250854 Remove `vue.esm` and use `vue.runtime.esm` instead

config/default.json, core/build/webpack.prod.sw.config.ts, core/modules/initial-resources/clientResourcesLoader.ts, core/modules/initial-resources/serverResourcesFilter.ts, core/service-worker/core-service-worker.js, src/themes/icmaa-imp/assets/flags/README.md, src/themes/icmaa-imp/components/core/blocks/FlagIcon.vue
* The workbox-precache was loading all application assets in idle-mode which leads to a lot unnecessary requests for the user and we don't really need this, as our application isn't available offline due to needed catalog- and cart-requests
* I filtered `.map` files from preload and prefetch links in the SSR respone `<head>`
* I also added a allow-list to the preload and prefetch config-filter for initial-ressources so we have better control of what is prefetched or -loaded
* The flag-component caused all flag SVGs to be loaded because of a variable in the component require statement  and those flags caused a lot unnecessary requests
TCK-250854
=> #250854 Improve `prefetch`, `preload` and `precache` of application assets to save requests

src/themes/icmaa-imp/components/core/blocks/AddToCartSidebar/BundleSelector.vue
* If the child product of a bundle isn't visible and therefore not in the catalog, the `BundleSelector` component drops an error.
* I've updated the component to not fail for this edge-case and update the VSF indexer to pump the product-links name into the catalog
TCK-253999
=> #253999 Bugfix for missing products in product-links of bundled products

src/themes/icmaa-imp/components/core/blocks/SearchPanel/SearchPanel.vue
* to limit results in GA by only final search requests and not the slow-typping sub-requests
TCK-253983
=> #253983 Debounce GTM search-event

src/themes/icmaa-imp/components/core/blocks/Reviews/ReviewsList.vue, src/themes/icmaa-imp/pages/Product.vue
* Remove old `itemProps` from DOM
* Remove `RecentlyViewedModule` integration
* Don't hide reviews if offline
=> Bugfix for reviews on PDP

src/modules/icmaa-newsletter/pages/Newsletter.vue
content is maintained via Storyblok
```
header:
img: impericon/newsletter/20220713_anmeldeseite_nl_header_en.jpg
alt: Impericon Newsletter
whys .....
```
TCK-257310
=> #257310 Add header to newsletter subscription-page

src/modules/icmaa-cms/components/Wrapper.vue, src/modules/icmaa-cms/helpers/index.ts, src/themes/icmaa-imp/components/core/blocks/CategoryExtras/Footer.vue, src/themes/icmaa-imp/components/core/blocks/RichText.vue
* Added image support for block-wrapper and `stingToComponent` method
* Refactor `stingToComponent` to support custom styling per tag
* Improve styling of category-footer and add block-wrapper for new `ceContentFooter` field
* Improve styling in block-wrapper and add new `icmaa-rte`/`component_rte` component
TCK-258705
=> #258705 Add new RTE support for block-wrapper and add blocks to footer

src/themes/icmaa-imp/components/core/blocks/Footer/Footer.vue
… Releaseversion "footer-links" in Storyblok for all languages was created.
```
"carrierLogos": [
{
"name": "PayPal",
"path": "paypal",
"route": "/service-payment"
},
{
"name": "Klarna",
"path": "klarna",
"route": "/service-payment"
},
{
"name": "DHL",
"path": "dhl",
"route": "/service-shipping"
},
{
"name": "Visa",
"path": "visa",
"route": "/service-payment"
},
{
"name": "MasterCard",
"path": "mastercard",
"route": "/service-payment"
},
{
"name": "FedEx",
"path": "fdx",
"route": "/service-shipping"
}
],
```
TCK-255405
=> #255405 Add custom link to the carrier logos

src/modules/icmaa-competitions/pages/Competition.vue
* Add an optional caption and/or image after submitting the competitions. This can be used to directly display coupons or other promotions.
TCK-263116
=> #263116 Add simple success content to competitions

core/modules/cart/helpers/syncCartWhenLocalStorageChange.ts, core/modules/cart/store/mutation-types.ts, core/modules/cart/store/mutations.ts
* We can't use the cart-mutations for the localstorage-sync because they would create an infinite-loop between the windows. Thats why we create a copy of this method with a suffix so the subscrided mutations won't get called again.
TCK-261112
=> #261112 Bugfix for race-condition and infinite-loop in cart local-storage-sync

src/themes/icmaa-imp/components/core/blocks/Checkout/PersonalDetails.vue
* This reverts commit e0a6170043abf48aeec561a3c7c264e83c6ed41e and is related to:  
https://github.com/icmaa/magento/pull/1430
* We now can disable the PayPal button in the backend
TCK-263774
=> Revert "#263774 Hide PayPal's checkout button until the bugfix (#874)"

src/modules/icmaa-meta/mixins/categoryMeta.ts, src/modules/icmaa-meta/mixins/productMeta.ts, src/themes/icmaa-imp/components/core/blocks/CategoryExtras/Header.vue, src/themes/icmaa-imp/components/core/blocks/Picture.vue
* #265975 Add `meta_description` to meta-tags
* #265822 Add category-header to as `<link rel="preload" />` tag
Related to https://github.com/icmaa/magento/pull/1433
TCK-265822, TCK-265975
=> #265822 & #265975 SEO optimizations

core/i18n/resource/i18n/de-DE.csv, core/i18n/resource/i18n/en-US.csv, src/modules/icmaa-tracking/README.md, src/modules/icmaa-tracking/components/TrackingLink.vue, src/modules/icmaa-tracking/index.ts, src/modules/icmaa-tracking/pages/Tracking.vue, src/modules/icmaa-tracking/routes.ts
Related to: https://github.com/icmaa/shop-workspace/commit/fc8dc1a25509b26d6dbe1cff40c0fee8afc3b939
TCK-268886
=> #268886 Add Paqato tracking to customer-account and add custom `/order-tracking` route

src/modules/icmaa-google-tag-manager/store/index.ts, src/themes/icmaa-imp/pages/Product.vue
* Connected to https://github.com/icmaa/shop-workspace/commit/d3769108b3b132f68faa75f9d8a5cd7846be4d65
TCK-275506
=> #275506 Use the SKU/ID of the parent product in data-layer on PDP

docker/vue-storefront/Dockerfile, src/modules/icmaa-checkout/pages/Checkout.ts, src/modules/icmaa-teaser/store/actions.ts, src/modules/icmaa-user/index.ts, src/themes/icmaa-imp/components/core/blocks/Auth/Login.vue, src/themes/icmaa-imp/components/core/blocks/Checkout/Shipping/AdditionalCharges.vue, src/themes/icmaa-imp/pages/Home.vue, src/themes/icmaa-imp/store/ui.ts, src/themes/icmaa-imp/test/e2e/integration/Checkout/paymentCreditcard.spec.ts, src/themes/icmaa-imp/test/e2e/support/commands.ts
* Update acceptance-tests (#911)
* Add `gh` GitHub CLI tool to `devcontainer` (#910)
* #275958 Add redirect after necessary login for `/my-account/*` (#909)
* #277512 Bugfix for possible string-injection in checkout (#912)
* #275958 Bugfix for account redirect-paths /w parameters (#913)
* Update name of Storyblok datasource for `teaser-tags` (#914)
=> Release 2023-04-28

core/helpers/index.ts, core/test/unit/helpers/buildFilterProductsQuery.spec.ts
* This is related to: https://github.com/icmaa/magento/pull/1490
TCK-266752
=> #266752 Remove inherited category-id filter from `baseFilterProductsQuery`

core/helpers/index.ts, core/test/unit/helpers/buildFilterProductsQuery.spec.ts, src/themes/icmaa-imp/pages/Category.vue
* #266752 Remove inherited category-id filter from `baseFilterProductsQuery` (#939)
* Revert "#282012 Increase product-count on CLP to 24" (#940)
=> Release 2023-07-26

src/modules/icmaa-blog/components/List.vue, src/modules/icmaa-blog/components/ListCategoryHeadline.vue
* Use headline, if given, over category-name
* Don't show links in headline, if it is not a category-list
TCK-278156
=> #278156 Improve `icmaa-blog` headlines

src/modules/icmaa-meta/mixins/categoryMeta.ts
=> #302646 Remove pagination param from canonical URL on CLP
