icmaa/vue-storefront

- src/modules/icmaa-cms/hooks/beforeRegistration.ts
- src/modules/icmaa-cms/index.ts
- src/modules/icmaa-cms/store/block/actions.ts
- src/modules/icmaa-cms/store/block/index.ts
* Improve cache handling by using own collection like in other modules
> icmaa-cms // Improve cache handling

- src/modules/icmaa-category/pages/List.vue
- src/themes/icmaa-imp/components/core/Logo.vue
- src/themes/icmaa-imp/components/core/blocks/ICMAA/Cms/Pages/Service.vue
- src/themes/icmaa-imp/css/_README.md
- src/themes/icmaa-imp/css/base/_fonts.scss
- src/themes/icmaa-imp/css/base/_icons.scss
- src/themes/icmaa-imp/css/base/_text.scss
- src/themes/icmaa-imp/css/layout/_border.scss
- src/themes/icmaa-imp/css/layout/_layout.scss
- src/themes/icmaa-imp/css/layout/_margin.scss
- src/themes/icmaa-imp/css/layout/_padding.scss
- src/themes/icmaa-imp/css/main.scss
- src/themes/icmaa-imp/css/utilities/_utilities.scss
- src/themes/icmaa-imp/css/utilities/_visibility.scss
- src/themes/icmaa-imp/css/variables/_grid.scss
- src/themes/icmaa-imp/css/vendor/_flexboxgrid2.scss
- src/themes/icmaa-imp/package.json
- src/themes/icmaa-imp/tailwind.js
- src/themes/icmaa-imp/webpack.config.js
* Import Tailwind CC and include it into webpack build
* Include Tailwind with prefix "t-" and consolidate pixel values of original theme
* Add example CMS page (/service)
> Include tailwind.css and style an example cms page (/service)

- src/themes/icmaa-imp/package.json
- src/themes/icmaa-imp/webpack.config.js
* Fix bug in config and dependencies
> Bugfix // Tailwind CSS vs. extending webpack config

- src/modules/icmaa-cms/mixins/categoryExtras.ts
- src/modules/icmaa-cms/package.json
- src/modules/icmaa-cms/store/abstract/actions.ts
- src/modules/icmaa-cms/store/block/actions.ts
- src/modules/icmaa-cms/store/category-extras/actions.ts
- src/modules/icmaa-cms/store/page/actions.ts
- src/themes/icmaa-imp/pages/Category.vue
* also improve some icmaa-cms code
> Load category-extras on category page via icmaa-cms module

- src/modules/icmaa-cms/mixins/categoryExtras.ts
- src/modules/icmaa-cms/store/category-extras/getters.ts
- src/themes/icmaa-imp/components/core/blocks/ICMAA/CategoryExtras/Header.vue
- src/themes/icmaa-imp/pages/Category.vue
* Create first block draft for category page
> Extend icmaa-cms/category-extras to get current extras

- src/modules/icmaa-category/index.ts
- src/modules/icmaa-category/store/category/CategoryState.ts
- src/modules/icmaa-category/store/category/actions.ts
- src/modules/icmaa-category/store/category/getters.ts
- src/modules/icmaa-category/store/category/index.ts
- src/modules/icmaa-category/store/category/mutation-types.ts
- src/modules/icmaa-category/store/category/mutations.ts
- src/modules/icmaa-cms/mixins/categoryExtras.ts
- src/modules/icmaa-cms/store/category-extras/getters.ts
- src/modules/icmaa-url/store/actions.ts
- src/themes/icmaa-imp/pages/Category.vue
* Change `category-next/getCurrentCategory` as module extension and implement it into our modules
* @todo: remove module-extension when #3295 is approved and merged
> #3286 Improve catalog-next module 

- core/modules/catalog/components/Search.ts
- src/modules/icmaa-category/components/List.ts
- src/modules/icmaa-category/index.ts
- src/modules/icmaa-cms/index.ts
- src/modules/icmaa-url/index.ts
- src/themes/icmaa-imp/components/core/blocks/SearchPanel/SearchPanel.vue
- src/themes/icmaa-imp/components/core/blocks/Wishlist/Product.vue
- src/themes/icmaa-imp/components/core/blocks/Wishlist/RemoveButton.vue
- src/themes/icmaa-imp/components/core/blocks/Wishlist/Wishlist.vue
- src/themes/icmaa-imp/css/base/_base.scss
- src/themes/icmaa-imp/store/claims.ts
* Fix wrong library links (due changes in develop branch)
* Fix styling of mobile inputs
* Fix 'null' search-input bug
* Improve style of wishlist (crude draft)
> Small improvements

- src/themes/icmaa-imp/components/core/blocks/Footer/Footer.vue
- src/themes/icmaa-imp/package.json
- src/themes/icmaa-imp/webpack.config.js
* Remove unused CSS class (Tailwind) using PurgeCSS
* Add `postcss-clean` for minification of CSS
> #183264 Minify and purge CSS via webpack

- src/modules/icmaa-cms/helpers/index.ts
- src/modules/icmaa-cms/store/abstract/actions.ts
* To get the CMS content by storecode instead of language
> #181689 Add CMS request by storecode

- src/themes/icmaa-imp/components/core/blocks/Header/MetaNavigation.vue
- src/themes/icmaa-imp/pages/PageNotFound.vue
* Small VueJS `for-in`-index bug in MetaNavigation.vue
* Add correct status-code to 404 page (SEO)
> Small bugfixes on templates

- core/client-entry.ts
- core/lib/router-manager.ts
- core/modules/url/router/beforeEach.ts
* !!! This commit might be reverted when the fix is rolled out on develop to solve conflicts
* Changes came from PR DivanteLtd#3499
> Bugfix // #3485 Fix problems on homepage

- src/themes/icmaa-imp/components/core/ProductGallery.vue
- src/themes/icmaa-imp/components/core/blocks/Reviews/ReviewsClaim.vue
- src/themes/icmaa-imp/pages/Product.vue
* Fix bug while loading claim
* Remove related products until they are not ready
* Add min-height to product image to prevent flickering and remove bottom margin bug
> #186141 Small improvements for PDP

- src/modules/icmaa-category/README.md
- src/modules/icmaa-category/index.ts
- src/modules/icmaa-category/routes.ts
- src/modules/icmaa-config/index.ts
- src/themes/icmaa-imp/layouts/Default.vue
- src/themes/icmaa-imp/layouts/Minimal.vue
- src/themes/icmaa-imp/router/index.ts
* `icmaa-category` // Load custom-routes from module
* `icmaa-config` // Set initial state from module hook
> Improve icmaa-module code

- src/modules/icmaa-cms/store/abstract/actions.ts
- src/themes/icmaa-imp/store/ui.ts
* Remove default viewport state
* Change type `any` in `ListOptionsInterface`
> Add small bugfixes

- src/modules/client.ts
- src/modules/icmaa-catalog/components/Product.ts
- src/modules/icmaa-category-extras/helpers/categoryExtras/logo.ts
- src/modules/icmaa-category-extras/store/getters.ts
- src/modules/icmaa-user/.gitignore
- src/modules/icmaa-user/README.md
- src/modules/icmaa-user/index.ts
- src/modules/icmaa-user/package.json
- src/modules/icmaa-user/store/actions.ts
- src/modules/icmaa-user/store/getters.ts
- src/modules/icmaa-user/store/index.ts
- src/modules/icmaa-user/store/mutation-types.ts
- src/modules/icmaa-user/store/mutations.ts
- src/modules/icmaa-user/types/UserProfile.ts
- src/modules/icmaa-user/types/UserState.ts
- src/themes/default/components/core/Modal.vue
- src/themes/icmaa-imp/components/core/blocks/Auth/SignUp.vue
- src/themes/icmaa-imp/components/core/blocks/CategoryExtras/DepartmentLogo.vue
- src/themes/icmaa-imp/components/core/blocks/CategoryExtras/Header.vue
- src/themes/icmaa-imp/components/core/blocks/Header/ButtonAccount.vue
- src/themes/icmaa-imp/components/core/blocks/SidebarMenu/SidebarMenu.vue
* Create ´icmaa-user´ module
* Add action, getter and setter for cluster
* Save cluster to local-storage
* Fix account-button logic to consider login state
* Set cluster on PDP view and on click on department-logo
> #185323 Ser customer-cluster

- src/modules/icmaa-teaser/mixins/teaserMixin.ts
- src/modules/icmaa-teaser/types/TeaserState.ts
- src/themes/icmaa-imp/components/core/blocks/Teaser/Teaser.vue
- src/themes/icmaa-imp/components/core/blocks/Teaser/TeaserLarge.vue
- src/themes/icmaa-imp/components/core/blocks/Teaser/TeaserSmall.vue
- src/themes/icmaa-imp/components/core/blocks/Teaser/TeaserSmallRow.vue
- src/themes/icmaa-imp/pages/Home.vue
* Add fallback background color
* Add new teaser theme with 4 in a row
* Add teaser mixin and consolidate code
> #187932 Improve teaser module

- src/themes/icmaa-imp/components/core/blocks/AddToCartSidebar/AddToCartSidebar.vue
- src/themes/icmaa-imp/components/core/blocks/AddToCartSidebar/DefaultSelector.vue
- src/themes/icmaa-imp/components/core/blocks/Category/Filter/PriceSelector.vue
- src/themes/icmaa-imp/mixins/filterMixin.ts
- src/themes/icmaa-imp/webpack.config.js
* Fix add-to-cart bug (caused by wrong namespacing in mixin)
* Bugfix for price-slider – Whitelist CSS classes and import regarding no-srr
> #188009 Product-list-view bugfixes

- src/themes/icmaa-imp/components/core/blocks/Placeholder.vue
- src/themes/icmaa-imp/components/core/blocks/Teaser/Teaser.vue
- src/themes/icmaa-imp/pages/Home.vue
* Improve lazy-hydration on homepage
* Add placeholder for teaser
> Improve lazy loading

- src/themes/icmaa-imp/components/core/ProductTile.vue
- src/themes/icmaa-imp/components/core/blocks/Placeholder.vue
- src/themes/icmaa-imp/components/core/blocks/RetinaImage.vue
- src/themes/icmaa-imp/components/core/blocks/Teaser/Teaser.vue
- src/themes/icmaa-imp/components/core/blocks/Teaser/TeaserLarge.vue
- src/themes/icmaa-imp/components/core/blocks/Teaser/TeaserSmall.vue
- src/themes/icmaa-imp/components/core/blocks/Teaser/TeaserSmallRow.vue
* Prevent flickering while loading product-images and teaser
> Add placeholder to teaser and product-tile

- src/themes/icmaa-imp/components/core/blocks/SidebarMenu/NavigationItem.vue
- src/themes/icmaa-imp/components/core/blocks/Wishlist/Product.vue
- src/themes/icmaa-imp/components/core/blocks/Wishlist/Wishlist.vue
* Fix CSS bugs in wishlist sidebar
* Add small title to sidebar-navigation icon items
> Small CSS optimizations

- src/modules/icmaa-catalog/index.ts
- src/modules/icmaa-catalog/store/search-alias/actions.ts
- src/modules/icmaa-catalog/store/search-alias/getters.ts
- src/modules/icmaa-catalog/store/search-alias/index.ts
- src/modules/icmaa-catalog/store/search-alias/mutation-types.ts
- src/modules/icmaa-catalog/store/search-alias/mutations.ts
- src/modules/icmaa-catalog/types/SearchAliasState.ts
- src/modules/icmaa-config/index.ts
- src/themes/icmaa-imp/components/core/blocks/SearchPanel/SearchPanel.vue
* Also improve code for `icmaa-config`
> #189054 Ass search-alias implementation

- src/modules/icmaa-catalog/store/search-alias/actions.ts
- src/themes/icmaa-imp/components/core/blocks/SearchPanel/SearchPanel.vue
- src/themes/icmaa-imp/mixins/viewportMixin.ts
* Small bugfix for search-alias action
* Use `lodash/debounce` to minimize function calls per second in search and `ui/viewport`
> Improve search and `ui/viewport`

- src/themes/icmaa-imp/components/core/Loader.vue
- src/themes/icmaa-imp/components/core/Modal.vue
- src/themes/icmaa-imp/components/core/blocks/Auth/FacebookLoginButton.vue
- src/themes/icmaa-imp/components/core/blocks/Auth/Login.vue
- src/themes/icmaa-imp/pages/MyAccount.vue
- src/themes/icmaa-imp/resource/i18n/de-DE.csv
- src/themes/icmaa-imp/resource/i18n/en-US.csv
* Style progress-overlay
* Fix some bugs in login-modal and login routine
* Remove login mixin
* Register facebook-logout event
> Improve login and progress-overlay

- src/modules/icmaa-review/components/MyAccount/MyOrderReview.vue
- src/themes/icmaa-imp/components/core/ProductTile.vue
- src/themes/icmaa-imp/components/core/blocks/Button.vue
- src/themes/icmaa-imp/components/core/blocks/MyAccount/MyProductAlerts.vue
- src/themes/icmaa-imp/components/core/blocks/MyAccount/MyProductAlerts/Product.vue
* Bugfix for order-review / Load products when order changed
* Style product-alerts by using product-tile (improve button & product-tile)
> Bugfix and improvement for my-account styling

- src/modules/icmaa-url/server.ts
- src/themes/icmaa-imp/pages/Product.vue
* And hide error message in products
> #191487 Redirect to default store when no store-code in URL

- src/modules/icmaa-category/helpers/index.ts
* Improve `icmaa/category-list` query by searching in category path
> Improvements

- .huskyrc.js
- src/themes/icmaa-imp/pages/Home.vue
- src/themes/icmaa-imp/webpack.config.js
> #192411 Remove debug code in notifications, fix post-css bug and more

- src/modules/icmaa-competitions/pages/Competition.vue
- src/themes/icmaa-imp/components/core/blocks/Footer/Footer.vue
- src/themes/icmaa-imp/components/core/blocks/Form/Form.vue
- src/themes/icmaa-imp/components/core/blocks/Teaser/Teaser.vue
- src/themes/icmaa-imp/components/core/blocks/Teaser/TeaserFullsize.vue
- src/themes/icmaa-imp/css/variables/_colors.scss
* Bugfix // Localize links in footer
* Style competitions description and move form component to template
* Add desktop fallback for fullsize teaser and improve placeholder ratios
> Small bug fixes

- src/modules/icmaa-google-tag-manager/components/GoogleCustomerReview.vue
better privacy, remove mail-address in DataLayer, because unnessesary
> #194211 - Criteo - Privacy

- src/modules/icmaa-review/components/MyAccount/MyOrderReview/Product.vue
- src/modules/icmaa-url/helpers/index.ts
- src/themes/icmaa-imp/components/core/blocks/AddToCartSidebar/AddToCartSidebar.vue
- src/themes/icmaa-imp/components/core/blocks/Microcart/Product.vue
- src/themes/icmaa-imp/components/core/blocks/MyAccount/MyOrder.vue
- src/themes/icmaa-imp/components/core/blocks/MyAccount/MyProductAlerts/Product.vue
- src/themes/icmaa-imp/components/core/blocks/Wishlist/Product.vue
- src/themes/icmaa-imp/mixins/product/priceMixin.ts
- src/themes/icmaa-imp/mixins/product/tileMixin.ts
* Show price in Add-To-Cart-Sidebar when product has different prices
* User custom `formatProductLink` method to hide `childSku` in product url's
> Bugfix // Show product price in add-to-cart sidebar and product url without child sku

- core/modules/catalog/helpers/index.ts
> Bugfix // `getVariantWithLowestPrice` uses inexistent `final_price` property

- src/modules/icmaa-catalog/store/category/actions/index.ts
- src/themes/icmaa-imp/components/core/blocks/AddToCartSidebar/AddToCartSidebar.vue
- src/themes/icmaa-imp/components/core/blocks/Category/Sidebar.vue
* Add stock-child-attribute-filter in `loadCategoryProducts` actions
* Sort filter in category sidebar
* Fix typo in add-to-cart sidebar
> Add child stock filter to list view and small bugfixes

- src/modules/icmaa-external-checkout/pages/ExternalSuccess.vue
closes #
Check your case. In case of any doubts please read about [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html)
**IMPORTANT NOTICE** - Remember to update `CHANGELOG.md` with description of your change
> Fixed cart not empty after checkout

- src/modules/icmaa-catalog/components/Category.ts
- src/modules/icmaa-catalog/components/Product.ts
- src/modules/icmaa-catalog/store/category/actions/index.ts
- src/modules/icmaa-catalog/store/product/actions.ts
- src/themes/icmaa-imp/components/core/ProductTile.vue
- src/themes/icmaa-imp/pages/Home.vue
* Add cache-tags to home, product and category page
* Bugfix for unisex product images in pdp
* Don't show image of selected product variant in product list – show parent product image
> Small bugfixes

- src/themes/icmaa-imp/pages/Home.vue
- remove teaserline "streetwear"
> Small Changes

- src/modules/icmaa-cart/store/actions.ts
- src/modules/icmaa-external-checkout/README.md
- src/modules/icmaa-external-checkout/helper/index.ts
- src/modules/icmaa-external-checkout/index.ts
- src/modules/icmaa-external-checkout/package.json
- src/modules/icmaa-external-checkout/pages/ExternalSuccess.vue
- src/modules/icmaa-external-checkout/server.ts
- src/modules/icmaa-url/server.ts
- yarn.lock
* Destroy Magento session cookie on logout
* Log user in after return to VSF
* Update quote-id in VSF after login in Magento
> #197484 Add bi-directional session handling to external-checkout

- src/modules/icmaa-external-checkout/pages/ExternalSuccess.vue
- src/modules/icmaa-google-tag-manager/components/GoogleCustomerReview.vue
- src/modules/icmaa-google-tag-manager/hooks/afterEach.ts
- src/modules/icmaa-google-tag-manager/hooks/afterRegistration.ts
- src/modules/icmaa-google-tag-manager/index.ts
- src/modules/icmaa-google-tag-manager/mixins/checkoutSuccessGtm.ts
- src/modules/icmaa-google-tag-manager/store/index.ts
- src/modules/icmaa-google-tag-manager/types/GoogleTagManagerState.ts
* Bugfix for client init load bug
* Only load GTM on client-side
* Improve `/order-success` event handling for GTM
* Consolidate code for `icmaa-google-tag-manager`
* Add email to `GoogleCustomerReviews`
* Add comment to `GoogleCustomerReview`
> #187376 Bugfixing for `icmaa-google-tag-manager`

- src/modules/icmaa-catalog/store/category/getters.ts
- src/modules/icmaa-twitter/helpers/index.ts
- src/themes/icmaa-imp/components/core/blocks/Category/SortBy.vue
- src/themes/icmaa-imp/components/core/blocks/CategoryExtras/Footer.vue
- src/themes/icmaa-imp/components/core/blocks/Footer/Footer.vue
- src/themes/icmaa-imp/components/core/blocks/Form/BaseInput.vue
- src/themes/icmaa-imp/components/core/blocks/Form/BaseSelect.vue
- src/themes/icmaa-imp/components/core/blocks/Form/BaseTextarea.vue
- src/themes/icmaa-imp/components/core/blocks/Header/MetaNavigation.vue
- src/themes/icmaa-imp/components/core/blocks/ICMAA/Cms/Pages/Festival.vue
- src/themes/icmaa-imp/components/core/blocks/ICMAA/Cms/Pages/ImpericonNeverSayDie.vue
- src/themes/icmaa-imp/components/core/blocks/SidebarMenu/NavigationItem.vue
- src/themes/icmaa-imp/components/core/blocks/SidebarMenu/SidebarMenu.vue
- src/themes/icmaa-imp/components/core/blocks/Teaser/EditButton.vue
- src/themes/icmaa-imp/components/core/blocks/Twitter/TwitterStatusBar.vue
- src/themes/icmaa-imp/components/core/blocks/Twitter/TwitterStatusFeed.vue
- src/themes/icmaa-imp/components/core/blocks/WebShare.vue
- src/themes/icmaa-imp/resource/meta/head.ts
- src/themes/icmaa-imp/test/e2e/integration/Menu/mainMeta.spec.ts
* `[user-scalable="no"]` is not used in the `<meta name="viewport">` element and the `[maximum-scale]` attribute is not less than 5
* Links to cross-origin destinations are unsafe
* Improve DOM validity in `icmaa-imp` theme
> Google-Lighthouse-Check Improvements 

- src/modules/icmaa-cms/data-resolver/Task.ts
- src/modules/icmaa-cms/store/default/actions.ts
- src/themes/icmaa-imp/components/core/blocks/Teaser/Teaser.vue
* Bugfix for custom cluster handling od `icmaa-teaser` components
* Switch `icmaa-cms` task-cache to in-memory mode
> Bugfixes for `icmaa-teaser` & enable in-memory cache-handling

- src/themes/icmaa-imp/components/core/CookieNotification.vue
- src/themes/icmaa-imp/components/core/blocks/Button.vue
* Improved cookie-accept button styling
> Cookie-accept button styling

- .github/workflows/build.yml
- .github/workflows/tests.yml
* Add shorter build time-out and use more unique build id to rerun tests as new run in Cypress dashboard
> Improve Github-Actions

- package.json
- src/modules/icmaa-catalog/store/category/actions/index.ts
- src/modules/icmaa-category/store/actions.ts
- src/modules/icmaa-recommendations/helpers/Rules.ts
- yarn.lock
* Rename our custom `SearchQuery` stock filter to support the new `storefront-query-builder`
* Update `package.json` and `yarn.lock`
> Update to `storefront-query-builder` version `1.0.0`

- core/modules/catalog-next/store/category/actions.ts
- package.json
- src/modules/icmaa-catalog/store/category/actions/index.ts
- src/modules/icmaa-category/store/actions.ts
- src/modules/icmaa-recommendations/helpers/Rules.ts
- src/modules/icmaa-teaser/resource/i18n/de-DE.csv
- src/modules/icmaa-teaser/server.ts
- src/themes/icmaa-imp/components/core/blocks/SearchPanel/CategoryPanel.vue
- src/themes/icmaa-imp/components/core/blocks/SearchPanel/SearchPanel.vue
- src/themes/icmaa-imp/resource/i18n/de-DE.csv
- src/themes/icmaa-imp/resource/i18n/en-US.csv
- yarn.lock
* #198002 Add CORS to `/default-translations.json` endpoint (#271)
* Merge `master` into `develop-2020-04-08` (#274)
* Update to `storefront-query-builder` version `1.0.0` (#273)
* #197501 Show category links in `SearchPanel` component (#275)
* #198002 Bugfix for `/default-translations.json` endpoint (#276)
> Release 2020-04-11

- src/modules/icmaa-catalog/store/category/actions/index.ts
- src/modules/icmaa-category/store/actions.ts
- src/modules/icmaa-recommendations/helpers/Rules.ts
- src/themes/icmaa-imp/components/core/blocks/SearchPanel/SearchPanel.vue
* Add our custom filter to `SearchPanel` component for custom search
* Improve some `applyFilter` commands (remove `scope`)
* Increase page-size of search-results in `SearchPanel` component
> Add our custom filter to `SearchPanel` component for custom search

- src/themes/icmaa-imp/components/core/blocks/SearchPanel/SearchPanel.vue
* Populate available categories from aggregation instead of the result products to show all possible products categories not just those who are on the current result page
> #197501 Improve `SearchPanel` category results

- .github/workflows/build.yml
- .github/workflows/tests.yml
- src/themes/icmaa-imp/components/core/blocks/SearchPanel/SearchPanel.vue
* Don't load aggregations on next pages
* Update `actions/setup-node` and `bahmutov/npm-install` versions in Github-Actions
> #197501 Improve `SearchPanel` component

- src/themes/icmaa-imp/layouts/Default.vue
- src/themes/icmaa-imp/resource/meta/head.ts
- src/themes/icmaa-imp/test/e2e/integration/Catalog/price.spec.ts
- src/themes/icmaa-imp/test/e2e/support/commands.ts
- src/themes/icmaa-imp/test/e2e/typings/index.d.ts
* Disable input-zoom for iOS
* Add valid `html-lang` attribute
* Bugfix for E2E price test
> #199586 Bugfix for iOS input-zoom and html-lang

- src/modules/icmaa-url/store/actions.ts
- src/themes/icmaa-imp/test/e2e/integration/Menu/languages.spec.ts
- src/themes/icmaa-imp/test/e2e/support/commands.ts
* Improve `mapFallbackUrl` in `icmaa-url`
* Bugfix for language E2E test
> Improve `icmaa-url`module and E2E tests

- src/modules/icmaa-config/helpers/price.ts
- src/modules/icmaa-config/index.ts
- src/modules/icmaa-google-tag-manager/store/index.ts
- src/modules/icmaa-tracking/components/TrackingLink.vue
- src/themes/icmaa-imp/components/core/blocks/MyAccount/MyOrder.vue
- src/themes/icmaa-imp/components/core/blocks/MyAccount/MyOrders.vue
* Add custom `formatValue` and `round` filter in `icmaa-config` module
* Bugfixes for price-formatting in `MyOrders` and several property-types
> #199702 Bugfixes for `MyOrders`, for property-types and add filters

- src/modules/icmaa-google-tag-manager/mixins/checkoutSuccessGtm.ts
* Also disable old analytics options again, as they don't make any differents
* Add `action: purchase` option to event
> #187376 Add correct children in orders of `icmaa-google-tag-manager`

- src/modules/icmaa-category/store/actions.ts
- src/modules/icmaa-user/store/actions.ts
- src/themes/icmaa-imp/components/core/blocks/MyAccount/MyAddresses.vue
- src/themes/icmaa-imp/components/core/blocks/MyAccount/Navigation.vue
- src/themes/icmaa-imp/components/core/blocks/Teaser/TeaserSplit.vue
- src/themes/icmaa-imp/pages/MyAccount.vue
- src/themes/icmaa-imp/test/e2e/integration/Customer/address.spec.ts
- src/themes/icmaa-imp/test/e2e/integration/Customer/customerAuth.spec.ts
- src/themes/icmaa-imp/test/e2e/support/commands.ts
- src/themes/icmaa-imp/test/e2e/typings/index.d.ts
* #200709 Bugfix for `customercluster` related content (#325)
* Add defaults for customer object when send to API to fullfil JSON schema (#326)
* Add E2E test for address-routine in customer account (#327)
* Added missing translate filter for text fields (#328)
> Release 2020-05-12

- src/themes/icmaa-imp/components/core/blocks/Product/ProductPreorder.vue
> #201056 Right Attribute for preorder date

- src/themes/icmaa-imp/components/core/blocks/Microcart/Product.vue
- src/themes/icmaa-imp/resource/i18n/de-DE.csv
* Fixed duplicate word in german tranlation
* Fixed wrong price display when using a coupon code
* Microcart product image links to product page
> #199761 Small layout fixes

- src/modules/icmaa-review/components/MyAccount/MyOrderReview.vue
- src/themes/icmaa-imp/components/core/blocks/MyAccount/Headline.vue
- src/themes/icmaa-imp/components/core/blocks/MyAccount/MyAddresses.vue
- src/themes/icmaa-imp/components/core/blocks/MyAccount/MyGiftcert.vue
- src/themes/icmaa-imp/components/core/blocks/MyAccount/MyNewsletter.vue
- src/themes/icmaa-imp/components/core/blocks/MyAccount/MyOrder.vue
- src/themes/icmaa-imp/components/core/blocks/MyAccount/MyOrders.vue
- src/themes/icmaa-imp/components/core/blocks/MyAccount/MyProductAlerts.vue
- src/themes/icmaa-imp/components/core/blocks/MyAccount/MyProfile.vue
- src/themes/icmaa-imp/components/core/blocks/MyAccount/Navigation.vue
* New design for customer account navigation
* Removed icons from account pages
> #200941 New design for customer account navigation

- src/themes/icmaa-imp/pages/ResetPassword.vue
- Show forgot password modal when email or token get parameters are missing
> #201742 Show forgot password modal

- src/modules/icmaa-cms/components/Wrapper.vue
- src/themes/icmaa-imp/test/e2e/integration/Catalog/teaser.spec.ts
- Added whitelist for url parameters
- Added cypress tests
> #201739 Hide teaser on category-page when GET params are set

- src/themes/icmaa-imp/components/core/blocks/ICMAA/Cms/Pages/DigitalEvents.vue
- src/themes/icmaa-imp/router/icmaa-cms/router.ts
> #202341 Added digital-events page

- src/modules/icmaa-category/helpers/index.ts
- src/modules/icmaa-category/store/actions.ts
- src/themes/icmaa-imp/test/e2e/integration/Catalog/landingpageAtoz.spec.ts
* Improve `icmaa-category` catgory list by adding multiple, relative target levels (#361)
> Merge latest `master` into integration branch

- src/modules/icmaa-catalog/index.ts
- src/modules/icmaa-monitoring/server.ts
* Make SSR exception more expressiv
* Bugfix for `Cannot read property 'price_incl_tax' of undefined` exception
> Bugfixes and improvements

- src/modules/icmaa-category/components/core/ProductListingWidget.vue
- src/modules/icmaa-category/pages/List.vue
* Now shows the latest 8 product from category "New" - depends on department
> #199699 Add `ProductListingWidget` to `icmaa-category-list`

- src/modules/icmaa-catalog/store/category/actions/index.ts
* Add custom `includeFields`/`excludeFields` loaded via getter
> Bugfix for `includeFields`/`excludeFields` in ticket-list-view

- core/i18n/resource/i18n/ar-SA.csv
- core/i18n/resource/i18n/cs-CZ.csv
- core/i18n/resource/i18n/de-DE.csv
- core/i18n/resource/i18n/en-US.csv
- core/i18n/resource/i18n/es-ES.csv
- core/i18n/resource/i18n/et-EE.csv
- core/i18n/resource/i18n/fi-FI.csv
- core/i18n/resource/i18n/fr-FR.csv
- core/i18n/resource/i18n/it-IT.csv
- core/i18n/resource/i18n/nl-NL.csv
- core/i18n/resource/i18n/pl-PL.csv
- core/i18n/resource/i18n/pt-BR.csv
- core/i18n/resource/i18n/pt-PT.csv
- core/i18n/resource/i18n/ru-RU.csv
- core/i18n/resource/i18n/zh-cn.csv
- core/lib/sync/task.ts
* Remove translation of log messages to be able to filter them
* Add more specific payload to several error logs
> Improve logging of VSF task manager

- src/index.amp.template.html
- src/modules/client.ts
- src/modules/icmaa-amp-renderer/index.ts
- src/modules/icmaa-meta/mixins/categoryMeta.ts
- src/modules/icmaa-meta/mixins/productMeta.ts
- src/modules/icmaa-monitoring/server.ts
- src/themes/icmaa-amp/components/core/ProductImageAmp.vue
- src/themes/icmaa-amp/pages/Category.vue
- src/themes/icmaa-imp/components/core/blocks/Product/ProductDetails.vue
- src/themes/icmaa-imp/pages/Product.vue
- src/themes/icmaa-imp/resource/i18n/cs-CZ.csv
- src/themes/icmaa-imp/resource/i18n/de-DE.csv
- src/themes/icmaa-imp/resource/i18n/en-US.csv
- src/themes/icmaa-imp/resource/i18n/es-ES.csv
- src/themes/icmaa-imp/resource/i18n/fi-FI.csv
- src/themes/icmaa-imp/resource/i18n/fr-FR.csv
- src/themes/icmaa-imp/resource/i18n/it-IT.csv
- src/themes/icmaa-imp/resource/i18n/pl-PL.csv
- src/themes/icmaa-imp/resource/i18n/pt-BR.csv
- src/themes/icmaa-imp/resource/i18n/sv-SE.csv
* #204222 Show `commonphrases` in description-tab on PDP (#383)
* #204338 Show out-of-stock message after stock-check on PDP (#382)
* #197499 Include feedback of datadog support team (#384)
* #203209 Bugfix and disable AMP implementation (#385)
> Release 2020-07-02

- config/default.json
- core/modules/catalog/helpers/variant/findConfigurableVariant.ts
- src/modules/icmaa-catalog/README.md
- src/themes/icmaa-imp/mixins/product/optionsMixin.ts
- src/themes/icmaa-imp/mixins/product/priceMixin.ts
* Add `selectOutOfStockVariants` config flag
* Add change to documentation
* Bugfix for `hasMultiplePrices` property
> Add `selectOutOfStockVariants` config flag and fix `hasMultiplePrices` property

- src/themes/icmaa-imp/test/e2e/integration/Search/search.spec.ts
* Search by alias using an account and add a word for "multi-term-search"
> #205098 Improve test for product search

- src/themes/icmaa-imp/components/core/blocks/Auth/Register.vue
- src/themes/icmaa-imp/components/core/blocks/Reviews/ReviewsClaim.vue
- src/themes/icmaa-imp/test/e2e/integration/Marketing/reviews.spec.ts
- src/themes/icmaa-imp/test/e2e/integration/Menu/languages.spec.ts
- src/themes/icmaa-imp/test/e2e/support/commands.ts
- src/themes/icmaa-imp/test/e2e/support/index.ts
- src/themes/icmaa-imp/test/e2e/typings/index.d.ts
* Fix the following tests which won't work after the changes of #392 & #394:
* `src/themes/icmaa-imp/test/e2e/integration/Menu/languages.spec.ts`
* `src/themes/icmaa-imp/test/e2e/integration/Marketing/reviews.spec.ts`
* `src/themes/icmaa-imp/test/e2e/integration/Menu/languages.spec.ts`
> #202369 Fix acceptance tests

- core/lib/router-manager.ts
- src/modules/icmaa-meta/helper/head/hreflang.ts
- src/modules/icmaa-url/README.md
- src/themes/icmaa-imp/resource/i18n/it-IT.csv
- src/themes/icmaa-imp/router/index.ts
* #205748 Improve url- and route-handling (#403)
* #206468 Add `/it` translation for `VAT number` (#404)
> Release 2020-07-29

- core/modules/url/helpers/transformUrl.ts
- src/modules/client.ts
- src/modules/icmaa-google-tag-manager/README.md
- src/modules/icmaa-google-tag-manager/components/GoogleCustomerReview.vue
- src/modules/icmaa-google-tag-manager/helpers/index.ts
- src/modules/icmaa-google-tag-manager/helpers/pageView.ts
- src/modules/icmaa-google-tag-manager/hooks/afterRegistration.ts
- src/modules/icmaa-google-tag-manager/hooks/index.ts
- src/modules/icmaa-google-tag-manager/index.ts
- src/modules/icmaa-google-tag-manager/package.json
- src/modules/icmaa-google-tag-manager/store/index.ts
- src/modules/icmaa-google-tag-manager/types/GoogleTagManagerState.ts
- src/modules/icmaa-url/store/actions.ts
- src/themes/icmaa-imp/pages/Category.vue
- src/themes/icmaa-imp/pages/Product.vue
* Bugfix for first page-load and tracking
* Use `router.meta` approach to differ between different page-types
* Improve "asynchronousity" of module registration
> #207954 Bugfix and improvements for `icmaa-google-tag-manager`

- src/modules/icmaa-google-tag-manager/hooks/afterRegistration.ts
* Also rename events to be consistent
> Add `quantity` value to GTM `addToCart` and `removeFromCart` events

- src/modules/icmaa-cart/store/actions.ts
- src/themes/icmaa-imp/mixins/product/addtocartMixin.ts
* #210379 Bugfix for add-to-cart routine and login to existing quote (#437)
> Release 2020-09-15

- src/modules/icmaa-cart/store/index.ts
- src/modules/icmaa-catalog/store/attribute/mutations.ts
- src/themes/icmaa-imp/components/core/blocks/Form/BaseSelect.vue
- src/themes/icmaa-imp/components/core/blocks/Microcart/Product.vue
- src/themes/icmaa-imp/components/core/blocks/Teaser/Teaser.vue
- yarn.lock
* Add qty update to cart
* Bugfix for wrong index in Teaser component
* Small improvements in `icmaa-*` modules
* Update `yarn.lock`
> General improvements

- core/data-resolver/CategoryService.ts
- core/data-resolver/types/DataResolver.d.ts
- core/i18n/resource/i18n/en-US.csv
- core/i18n/resource/i18n/it-IT.csv
- core/modules/catalog-next/store/category/getters.ts
- src/modules/icmaa-catalog/components/Product.ts
- src/modules/icmaa-catalog/store/category/actions/index.ts
- src/modules/icmaa-catalog/store/product/actions.ts
- src/modules/icmaa-category-extras/README.md
- src/modules/icmaa-category-extras/helpers/index.ts
- src/modules/icmaa-category-extras/store/actions.ts
- src/modules/icmaa-category-extras/store/getters.ts
- src/modules/icmaa-category-extras/store/index.ts
- src/modules/icmaa-category-extras/store/mutations.ts
- src/modules/icmaa-category-extras/types/CategoryExtrasState.ts
- src/themes/icmaa-imp/components/core/ProductImage.vue
- src/themes/icmaa-imp/components/core/blocks/CategoryExtras/Header.vue
- src/themes/icmaa-imp/components/core/blocks/CategoryExtras/LogoLine.vue
- src/themes/icmaa-imp/components/core/blocks/Picture.vue
- src/themes/icmaa-imp/mixins/lozadMixin.ts
- src/themes/icmaa-imp/pages/Category.vue
- src/themes/icmaa-imp/pages/Product.vue
- src/themes/icmaa-imp/resource/i18n/en-US.csv
* #211292 Refactor how department/account related content is fetched (#451)
* Improve category-extras and -banner on PDP and CLP (#452)
* Improve loading of category-extras and breadcrumbs (#454)
> Release 2020-09-30

- src/themes/icmaa-imp/components/core/blocks/CategoryExtras/Header.vue
- src/themes/icmaa-imp/pages/Product.vue
* Bugfix for wrapping add-to-cart button on tablet viewport
* Add link to category on category-header
> Improve styling and add category link on PDP

- src/modules/icmaa-meta/mixins/categoryMeta.ts
- src/themes/icmaa-imp/components/core/blocks/CategoryExtras/Footer.vue
- src/themes/icmaa-imp/pages/Category.vue
* Change headline from `title` to `category.name` for correct translation
> #212232 Change category headline

- src/modules/icmaa-external-checkout/index.ts
* On our production system it won't work because of a redirection that removes the tailing slash
> Bugfix for exception during fetch of http-only-cookie-deletion

- src/themes/icmaa-imp/pages/Category.vue
* This also has been removed in default-theme: https://github.com/DivanteLtd/vsf-default/commit/f3069bd1bf0659b63fcf935e25f52f830ed3c41a
> #212608 Always reload products on category change in CLP

- src/modules/icmaa-google-tag-manager/hooks/afterRegistration.ts
- src/modules/icmaa-google-tag-manager/hooks/index.ts
- src/modules/icmaa-google-tag-manager/mixins/checkoutSuccessGtm.ts
- src/themes/icmaa-imp/components/core/blocks/Auth/FacebookLoginButton.vue
- src/themes/icmaa-imp/hooks/ui.ts
- src/themes/icmaa-imp/pages/Category.vue
* #212608 Add GTM event for Facebook-login-button click (#469)  …
* #212610 Always reload products on category change in CLP (#470)
> Release 2020-10-16

- src/themes/icmaa-imp/pages/Home.vue
* Update logoline for fashion on homepage (#472)
> Release 2020-10-20

- src/themes/icmaa-imp/components/core/blocks/MyAccount/MyOrder.vue
- src/themes/icmaa-imp/resource/i18n/de-DE.csv
- src/themes/icmaa-imp/resource/i18n/en-US.csv
* Show subtotals including taxes
* Show cash-on-delivery fee
* Show priority-service fee
* Only show discount if it exists
> Improve totals on customers order-details page

- src/modules/icmaa-catalog/store/category/actions/search.ts
- src/themes/icmaa-imp/components/core/blocks/MyAccount/MyOrder.vue
* Bugfix for `loadMoreSearchProducts` action when using alias
* Use new attribute-codes for priority-handling for `MyOrders` component
* Add priority-handling text to shipping information in order-details
> Bugfix for search-results and optimizations on order-details

- .github/workflows/build.yml
- .github/workflows/tests.yml
- core/data-resolver/UserService.ts
- core/data-resolver/types/DataResolver.d.ts
- core/lib/sync/task.ts
- core/modules/cart/store/actions/synchronizeActions.ts
- core/modules/user/store/actions.ts
- src/modules/icmaa-cart/README.md
- src/modules/icmaa-cart/helpers/index.ts
- src/modules/icmaa-cart/helpers/notifications.ts
- src/modules/icmaa-cart/store/actions.ts
- src/modules/icmaa-cart/store/getters.ts
- src/modules/icmaa-cart/store/index.ts
- src/modules/icmaa-user/README.md
- src/modules/icmaa-user/store/actions.ts
- src/themes/icmaa-imp/components/core/blocks/Auth/Register.vue
- src/themes/icmaa-imp/components/core/blocks/Microcart/Product.vue
- src/themes/icmaa-imp/mixins/product/addtocartMixin.ts
- src/themes/icmaa-imp/pages/MyAccount.vue
* Update Github actions (#488)
* #214982 & #215028 Add JWT expiration-time and improve session-health (#489)
> Release 2020-11-19

- src/modules/icmaa-cms/components/Wrapper.vue
- src/modules/icmaa-competitions/pages/Competition.vue
- src/modules/icmaa-config/helpers/datetime.ts
- src/themes/icmaa-imp/components/core/blocks/CategoryExtras/Footer.vue
- src/themes/icmaa-imp/components/core/blocks/ICMAA/Cms/Pages/XmasCalendar.vue
- src/themes/icmaa-imp/components/core/blocks/Picture.vue
- src/themes/icmaa-imp/router/icmaa-cms/router.ts
* #212810 Add components and changes for x-mas-calendar (#492)
> Release 2020-11-24

- src/themes/icmaa-imp/components/core/blocks/CategoryExtras/Footer.vue
- src/themes/icmaa-imp/mixins/product/featuresMixin.ts
- src/themes/icmaa-imp/pages/PageNotFound.vue
* #216193 Show missing product-features on PDP (#503)
* #216951 Bugfix for description in footer of CLP (#504)
* Correct Link-Style (w/o whitespace) at 404-Page (#506)
> Release 2020-12-08

- src/modules/icmaa-competitions/pages/Competition.vue
- src/themes/icmaa-imp/components/core/NewsletterPopup.vue
* Only if newsletter checkbox is selected and an email is available
> #217076 Automatically subscribe to newsletter in `icmaa-competitions` module

- src/modules/icmaa-config/helpers/validators.ts
- src/themes/icmaa-imp/components/core/blocks/MyAccount/MyAddresses.vue
- src/themes/icmaa-imp/resource/i18n/de-DE.csv
- src/themes/icmaa-imp/resource/i18n/en-US.csv
* Check for leading or tailing numbers inside words of street-address to prevent missing spaces
> #212674 Improve address-validation for housenumber

- src/themes/icmaa-imp/components/core/blocks/ICMAA/Cms/Pages/XmasCalendar.vue
* Without this fix the last day won't open.
> Hotfix for end-date of xmas-calendar

- src/themes/icmaa-imp/resource/i18n/de-DE.csv
- src/themes/icmaa-imp/service-worker/index.js
* Add translations for product-list promo-banners (#522)
* #218052 Bugfix for service-worker rules for falsely cached API endpoints (#523)
> Release 2021-01-13

- src/modules/icmaa-advice/store/actions.ts
- src/modules/icmaa-advice/store/getters.ts
- src/modules/icmaa-advice/types/AdviceState.ts
- src/themes/icmaa-imp/components/core/blocks/Advice/Advice.vue
- src/themes/icmaa-imp/layouts/Default.vue
* Add activation by store-view
* Remove tags feature (doesn't make sense)
> Refactor `icmaa-advice` module

- src/modules/icmaa-cms/components/Lazyload.vue
- src/modules/icmaa-cms/mixins/isVisibleMixin.ts
- src/modules/icmaa-teaser/pages/TeaserQualityAssurance.vue
- src/modules/icmaa-teaser/store/getters.ts
- src/themes/icmaa-imp/components/core/Breadcrumbs.vue
- src/themes/icmaa-imp/components/core/blocks/Category/SortBy.vue
- src/themes/icmaa-imp/pages/SearchResult.vue
* Bugfix for exception in for breadcrumbs component
* #220957 Bugfix for client-side filters on search-result page
* Bugfix for sorting on CLP on client-side change
* #220686 Bugfix for teaser QA site
* #220686 Add `lazyload` component and mixin
> Major bugfixes

- src/modules/icmaa-google-tag-manager/mixins/checkoutSuccessGtm.ts
* See also config changes in icmaa/shop-workspace#18
> #220963 Add netto price attributes to checkout-success page in GTM module

- src/modules/icmaa-cms/components/Lazyload.vue
- src/modules/icmaa-cms/mixins/LazyloadMixin.ts
- src/modules/icmaa-google-tag-manager/mixins/checkoutSuccessGtm.ts
- src/modules/icmaa-teaser/pages/TeaserQualityAssurance.vue
- src/modules/icmaa-teaser/store/getters.ts
- src/themes/icmaa-imp/components/core/Breadcrumbs.vue
- src/themes/icmaa-imp/components/core/blocks/Category/SortBy.vue
- src/themes/icmaa-imp/components/core/blocks/Teaser/Teaser.vue
- src/themes/icmaa-imp/components/core/blocks/Teaser/TeaserSkeleton.vue
- src/themes/icmaa-imp/pages/SearchResult.vue
* Major bugfixes (#539)
* Bugfix for exception in for breadcrumbs component
* #220957 Bugfix for client-side filters on search-result page
* Bugfix for sorting on CLP on client-side change
* #220686 Bugfix for teaser QA site
* #220686 Add `lazyload` component and mixin
* #220963 Add netto price attributes to checkout-success page in GTM module (#540)
> Release 2021-02-02

- src/modules/icmaa-looks/components/Look.vue
- src/modules/icmaa-looks/pages/Looks.vue
* Products won't load when switching between looks
> Bugfix for `icmaa-looks` product-load on router interaction

- src/themes/icmaa-imp/App.vue
- src/themes/icmaa-imp/components/core/Breadcrumbs.vue
- src/themes/icmaa-imp/components/core/blocks/Checkout/ThankYouPage.vue
- src/themes/icmaa-imp/components/core/blocks/Header/Logo.vue
- src/themes/icmaa-imp/components/core/blocks/Header/MinimalHeader.vue
- src/themes/icmaa-imp/components/core/blocks/MyAccount/Navigation.vue
- src/themes/icmaa-imp/index.js
- src/themes/icmaa-imp/mixins/defaultMixins.ts
- src/themes/icmaa-imp/pages/Home.vue
- src/themes/icmaa-imp/pages/PageNotFound.vue
- src/themes/icmaa-imp/pages/ResetPassword.vue
- src/themes/icmaa-imp/test/e2e/integration/Customer/resetPassword.spec.ts
* I've added a global computed property using a global mixin to be able to reuse it and only have to change it in one place for the future.
> #222912 Add links to home route without tailing-slash

- package.json
- src/themes/icmaa-imp/components/core/NewsletterPopup.vue
- src/themes/icmaa-imp/components/core/blocks/Auth/Register.vue
- src/themes/icmaa-imp/components/core/blocks/Footer/Newsletter.vue
- src/themes/icmaa-imp/components/core/blocks/Switcher/Language.vue
- src/themes/icmaa-imp/mixins/flagMixin.ts
- src/themes/icmaa-imp/pages/PageNotFound.vue
- yarn.lock
* Improve code for language-switcher mixin
* Change use of `vue-i18n/place` attribute to slots
* Update PM2 service to v4.5.5
> #222918 Hotfix for random SSR exceptions

- src/themes/icmaa-imp/components/core/blocks/ICMAA/Cms/Pages/NextGeneration.vue
* Add picture component for responsive and preloaded images
> #218992 Improve Next-Generation Landingpage

- src/themes/icmaa-imp/components/core/blocks/Reviews/Reviews.vue
- src/themes/icmaa-imp/test/e2e/integration/Catalog/price.spec.ts
- src/themes/icmaa-imp/test/e2e/support/commands.ts
- src/themes/icmaa-imp/test/e2e/typings/index.d.ts
* Load using current parent-id or current id if simple product
> #223087 Bugfix for missing reviews on PDP

- src/modules/icmaa-looks/components/Look.vue
- src/themes/icmaa-imp/components/core/blocks/Auth/Register.vue
- src/themes/icmaa-imp/components/core/blocks/Category/PromoBanner.vue
- src/themes/icmaa-imp/components/core/blocks/Form/BaseInput.vue
- src/themes/icmaa-imp/components/core/blocks/MyAccount/MyProfile.vue
- src/themes/icmaa-imp/components/core/blocks/Teaser/Teaser.vue
- src/themes/icmaa-imp/components/core/blocks/Teaser/TeaserSmall.vue
* #224780 Add correct bottom-margin if more than 4 small teaser (#593)
* #223037 Add correct DOB date-format based on config (#594)
* #224199 Bugfix for wrong promo-banner in CLP (#595)
* Bugfix for SSR exception in `icmaa-looks` module (#596)
> Release 2021-03-22

- src/themes/icmaa-imp/components/core/blocks/Product/ProductGallery.vue
- src/themes/icmaa-imp/mixins/viewportMixin.ts
- src/themes/icmaa-imp/store/ui.ts
* Toggle PDP zoom on desktop via click
* Add `isTouchDevice` to `ui` store and trigger PDP zoom by this metric
> #220414 Updates for zoom on PDP

- core/modules/cart/helpers/syncCartWhenLocalStorageChange.ts
- package.json
- src/modules/icmaa-cms/mixins/LazyloadMixin.ts
- src/modules/icmaa-config/helpers/cleanTimeout.ts
- src/modules/icmaa-product-alert/mixins/productStockAlertMixin.ts
- src/themes/icmaa-imp/components/core/LanguageSwitcher.vue
- src/themes/icmaa-imp/components/core/ProductImage.vue
- src/themes/icmaa-imp/components/core/blocks/AsyncSidebar/LoadingError.vue
- src/themes/icmaa-imp/components/core/blocks/Auth/FacebookLoginButton.vue
- src/themes/icmaa-imp/components/core/blocks/Footer/Footer.vue
- src/themes/icmaa-imp/components/core/blocks/Picture.vue
- src/themes/icmaa-imp/components/core/blocks/Product/ProductGallery.vue
- src/themes/icmaa-imp/components/core/blocks/Reviews/Reviews.vue
- src/themes/icmaa-imp/mixins/lozadMixin.ts
- src/themes/icmaa-imp/mixins/viewportMixin.ts
- src/themes/icmaa-imp/pages/Product.vue
- src/themes/icmaa-imp/resource/i18n/cs-CZ.csv
- src/themes/icmaa-imp/resource/i18n/de-DE.csv
- src/themes/icmaa-imp/resource/i18n/en-US.csv
- src/themes/icmaa-imp/resource/i18n/es-ES.csv
- src/themes/icmaa-imp/resource/i18n/fi-FI.csv
- src/themes/icmaa-imp/resource/i18n/fr-FR.csv
- src/themes/icmaa-imp/resource/i18n/it-IT.csv
- src/themes/icmaa-imp/resource/i18n/pl-PL.csv
- src/themes/icmaa-imp/resource/i18n/pt-PT.csv
- src/themes/icmaa-imp/resource/i18n/sv-SE.csv
- src/themes/icmaa-imp/store/ui.ts
* #222842 Bugfixes for several memory leaks and more (#607)
* Enhanced support for multistore mode
* Add `removeEventListener` to avoid JS memory-leaks
* Add `clearTimeout` to avoid JS memory-leaks
* Disconnect `IntersectionObserver` to avoid JS memory-leaks
* Call `$off` for Vue `$on` api-events to avoid JS memory-leaks
* Add correct `yarn` and `node` version to `package.json`
* #220414 Updates for zoom on PDP (#608)
* Toggle PDP zoom on desktop via click
* Add `isTouchDevice` to `ui` store and trigger PDP zoom by this metric
* #225814 Translations for new bestseller sorting (#609)
> Release 2021-03-31

- src/themes/icmaa-imp/components/core/blocks/MyAccount/MyAddresses.vue
US -> State
UK -> Region
We have only one l18n File for english!
> #224849 - better UK - localization

- src/modules/icmaa-cart/store/getters.ts
- src/themes/icmaa-imp/components/core/blocks/Microcart/Coupon.vue
- src/themes/icmaa-imp/components/core/blocks/Microcart/CouponField.vue
> #214404 Add multiple giftcerts or coupons in micro-cart

- src/modules/icmaa-google-tag-manager/helpers/pageView.ts
- src/modules/icmaa-google-tag-manager/hooks/afterRegistration.ts
- src/modules/icmaa-google-tag-manager/store/index.ts
- src/themes/icmaa-imp/components/core/ProductTile.vue
- src/themes/icmaa-imp/components/core/blocks/Reviews/ReviewsList.vue
- src/themes/icmaa-imp/mixins/product/tileMixin.ts
- src/themes/icmaa-imp/pages/SearchResult.vue
* #224313 Bugfix: Load `urlPath` on each page-view event (#629)
* Bugfixes (#630):
* #226973 Add date to reviews on PDP
*  Remove use of `v-observe-visibility` in product-tile
* #226868 Update SRP when switching between results
> Release 2021-04-21

- src/modules/icmaa-external-checkout/index.ts
- src/modules/icmaa-external-checkout/pages/Success.vue
- src/modules/icmaa-google-tag-manager/mixins/checkoutSuccessGtm.ts
- src/modules/icmaa-user/hooks/index.ts
- src/modules/icmaa-user/store/actions.ts
* Refactor order-success GTM event to be triggered by `icmaa-external-checkout` module
* Add `session-after-authorized` event to event-bus to have an event for each state
> #227433 Refactor GTM order-success event 

- src/modules/icmaa-user/store/getters.ts
- src/themes/icmaa-imp/components/core/blocks/AsyncSidebar/TopButton.vue
- src/themes/icmaa-imp/components/core/blocks/Header/ButtonUiSidebar.vue
- src/themes/icmaa-imp/components/core/blocks/Navigation/ClusterNavigation.vue
- src/themes/icmaa-imp/components/core/blocks/Navigation/Item.vue
- src/themes/icmaa-imp/components/core/blocks/Navigation/Sidebar.vue
- src/themes/icmaa-imp/components/core/blocks/Navigation/SubNavigation.vue
- src/themes/icmaa-imp/layouts/Default.vue
- src/themes/icmaa-imp/pages/Category.vue
- src/themes/icmaa-imp/store/ui.ts
> #226629 Add 2nd layer to main-navigation

- src/modules/icmaa-google-tag-manager/store/index.ts
- add event based "documenTitle" to Datalayer (not important but nice!)
- clear enhanced e-commerce layer if cms-page-view is fired (recommendation from google, but nowhere seen it)
Redo second point - Although it is recommended by google, the effects cannot be estimated. No adjustment is currently necessary.
> #224313 Improve GTM tracking

- src/themes/icmaa-imp/components/core/blocks/CategoryExtras/Footer.vue
* Use CSS instead and prevent the original text
> #228825 Don't trim SEO text on PLP

- package.json
* There is a bug with the latest LTS `14.17.0` during cloud-build for GAE Flex, so fallback to the latest, working version of NodeJS.
* See here: https://github.com/GoogleCloudPlatform/nodejs-docker/issues/214
TCK-228722
> Bugfix for GAE deployment

- app-imp-prod.yaml
* This might help for downscaling but should lead into more latency during upscaling
> Allow higher CPU utilization for GAE

- package.json
* Revert changes from #655, there is already an open ticket in the GCP repo (I've linked it in the previous PR)
> Revert `node` package version to `^14`

- src/themes/icmaa-imp/components/core/blocks/Navigation/SubNavigation.vue
* #226629 Add support for custom tiles in sub-navigation sidebar (#664)
> Release 2021-06-03

- src/themes/icmaa-imp/components/core/blocks/ICMAA/Cms/Pages/NextGeneration.vue
use own comp. for universal-link
TCK-231481
> #231481 - NextGeneration - use own comp. for universal-link

- src/themes/icmaa-imp/resource/i18n/nl-NL.csv
> #228597 Translation

- src/modules/icmaa-google-tag-manager/store/index.ts
- src/themes/icmaa-imp/components/core/blocks/AsyncSidebar/LoadingSpinner.vue
- src/themes/icmaa-imp/components/core/blocks/Category/Sidebar.vue
- src/themes/icmaa-imp/components/core/blocks/ICMAA/Cms/Pages/NextGeneration.vue
- src/themes/icmaa-imp/components/core/blocks/Microcart/Microcart.vue
- src/themes/icmaa-imp/components/core/blocks/Navigation/ClusterNavigation.vue
- src/themes/icmaa-imp/components/core/blocks/Navigation/Sidebar.vue
- src/themes/icmaa-imp/components/core/blocks/Navigation/SubNavigation.vue
- src/themes/icmaa-imp/components/core/blocks/Wishlist/Wishlist.vue
- src/themes/icmaa-imp/resource/i18n/nl-NL.csv
- src/themes/icmaa-imp/store/ui.ts
* #226629 Remove teaser from subnavigation (#667)
* #231481 NextGeneration / Use universal-link component (#672)
* #228597 Translation (#674)
* #226629 Improve 2nd navigation layer (#675)
* #222888 Add image-url instead of path to GTM data-layer (#677)
> Release 2021-06-18

- src/modules/icmaa-google-tag-manager/components/GoogleCustomerReview.vue
Bugfix based by last refactoring of `success` Events
TCK-232106
> #232106 - Google Customer Review - Fix Eventname

- src/modules/icmaa-recommendations/store/actions.ts
> #236498 Sort recommendations on PDP by `ranking_shop_bestseller`

- .gitignore
- .vscode/settings.json
- .vscode/snippets.code-snippets
> Add VSCode settings and snippets to workspace

- core/data-resolver/CartService.ts
- src/modules/icmaa-cart/store/actions/couponActions.ts
- src/themes/icmaa-imp/components/core/blocks/Microcart/CouponField.vue
- src/themes/icmaa-imp/components/core/blocks/Microcart/Totals.vue
* Silent core `applyCoupon`/`removeCoupon` service methods
* Return response in `applyCoupon`/`removeCoupon` actions
* Handle response in `CouponField` component
* Show discount in totals
TCK-239721
> Improve UI messages for coupon-routine

- core/data-resolver/StockService.ts
> Silent stock-service to prevent error popup-overlays

- src/themes/icmaa-imp/test/e2e/integration/Catalog/addtocart.spec.ts
- src/themes/icmaa-imp/test/e2e/integration/Catalog/price.spec.ts
- src/themes/icmaa-imp/test/e2e/integration/Checkout/paymentCreditcard.spec.ts
- src/themes/icmaa-imp/test/e2e/support/commands.ts
- src/themes/icmaa-imp/test/e2e/typings/index.d.ts
> Check stock using the API request in Cypress.io acceptance tests

- src/themes/icmaa-imp/components/core/blocks/Auth/Register.vue
> #240997 Add hidden reCaptcha to register form (#711)

- src/modules/icmaa-paypal/components/Checkout/Button.vue
> #240994 Improve address-mapping for `icmaa-paypal` payment-method

- core/modules/cart/store/actions/mergeActions.ts
- core/modules/cart/test/unit/store/mergeActions.spec.ts
- src/modules/icmaa-cart/README.md
- src/modules/icmaa-cart/store/actions/connectActions.ts
- src/modules/icmaa-cart/store/actions/itemActions.ts
- src/modules/icmaa-cart/store/actions/synchronizeActions.ts
- src/themes/icmaa-imp/components/core/blocks/Microcart/Product.vue
- src/themes/icmaa-imp/components/core/blocks/Microcart/Totals.vue
- src/themes/icmaa-imp/mixins/product/addtocartMixin.ts
* #241768 & #243588 Bugfix to remove orphaned incentives in cart and more (#729)
> Release 2021-12-17

- src/modules/icmaa-google-tag-manager/mixins/checkoutSuccessGtm.ts
so we calculate the commission with the correct price incl. discount
TCK-245916
> #245916 - Add `discount_amount` in Datalayer for AWIN Tracking

- src/modules/icmaa-google-tag-manager/mixins/checkoutSuccessGtm.ts
> #245916 AWIN `discountAmount` without VAT

- src/modules/icmaa-payment/components/methods/bank-payment/Info.vue
Related to: https://github.com/icmaa/magento/pull/1323
TCK-246148
> #246148 Remove account-data for prepayment method

- src/modules/icmaa-catalog/store/category/actions.ts
- src/modules/icmaa-payment/components/methods/bank-payment/Info.vue
- src/themes/icmaa-imp/pages/Category.vue
* #242172 Bugfix for missing category-links on CLP (#743) 
* #246148 Remove account-data for prepayment method in checkout (#744)
> Release 2022-01-19

- src/modules/icmaa-config/helpers/validators.ts
> #246607 Improve US streetname validation

- src/themes/icmaa-imp/components/core/blocks/Category/ListOptions.vue
- src/themes/icmaa-imp/pages/Category.vue
- src/themes/icmaa-imp/pages/SearchResult.vue
* We hope to decrease latency and network traffic on CLP requests as these responses are really heavy.
TCK-246997
> #246997 Change CLP to 16 items per page

- app-imp-prod.yaml
- core/lib/search/adapter/api-search-query/searchAdapter.ts
- src/modules/icmaa-config/Error.ts
- src/modules/icmaa-logs/lib/gcloud/helper.ts
> #246013 Improve error-logging for catalog-requests in GCP and scale-down GAE

- core/helpers/router.ts
- src/modules/icmaa-catalog/helpers/popState.ts
- src/modules/icmaa-catalog/index.ts
- src/themes/icmaa-imp/pages/Category.vue
> #221258 Support for client-side history-back support on CLP infinite-scrolling

- src/themes/icmaa-imp/components/core/blocks/SearchPanel/SearchPanel.vue
- src/themes/icmaa-imp/pages/Category.vue
- src/themes/icmaa-imp/pages/SearchResult.vue
* Make it even a bit more bulletproof and fix some stylings in search-sidebar
TCK-221258
> #221258 Small improvements for browser-back in CLP

- src/modules/icmaa-catalog/components/Product.ts
- src/modules/icmaa-catalog/helpers/index.ts
- src/modules/icmaa-catalog/helpers/productQtyByType.ts
- src/modules/icmaa-google-tag-manager/components/jsonld/JsonLdContainer.vue
- src/modules/icmaa-google-tag-manager/components/jsonld/JsonLdLoader.vue
- src/modules/icmaa-google-tag-manager/components/jsonld/Product.vue
- src/themes/icmaa-imp/components/core/blocks/Product/ProductAvailability.vue
- src/themes/icmaa-imp/pages/Product.vue
> #248913 Add structured-data to PDP

- src/modules/icmaa-google-tag-manager/components/jsonld/Product.vue
- src/themes/icmaa-imp/components/core/blocks/MyAccount/MyProfile.vue
- src/themes/icmaa-imp/pages/Error.vue
- src/themes/icmaa-imp/pages/MyAccount.vue
- src/themes/icmaa-imp/pages/ResetPassword.vue
- src/themes/icmaa-imp/pages/SearchResult.vue
> Improve `noindex, nofollow` settings for specific pages and more

- src/modules/icmaa-google-tag-manager/components/jsonld/Product.vue
* Add offers per child for configurable products
* Try to lazyload reviews and improve aggregated rating
TCK-248913
> #248913 Improve structured-data

- src/themes/icmaa-imp/pages/Category.vue
- src/themes/icmaa-imp/pages/SearchResult.vue
> #248473 Bugfix for history-back on CLP

- src/modules/icmaa-catalog/README.md
- src/themes/icmaa-imp/components/core/blocks/Category/Filter.vue
- src/themes/icmaa-imp/components/core/blocks/Category/Filter/ShortListSelector.vue
- src/themes/icmaa-imp/components/core/blocks/Category/Sidebar.vue
> #248473 Improve filter-sidebar on CLP

- core/scripts/server.h3.ts
- core/server/hooks.ts
- src/modules/icmaa-cdn/README.md
- src/modules/icmaa-cdn/server.h3.ts
> Add Cloudflare URL cache-bust by cache-tag

- src/themes/icmaa-imp/components/core/blocks/ProductTile/PromoBanner.vue
> #247581 Increase time for `New` promo-banner

- src/themes/icmaa-imp/pages/Category.vue
> #249450 Bugfix for browser-back in CLP

- core/scripts/server.h3.ts
- src/modules/icmaa-cdn/server.h3.ts
* Add complete CF cache-bust and improve catch of JSON errors (#776)
> Release 2022-03-09

- src/themes/icmaa-imp/pages/Category.vue
> #249450 Bugfix for browser-back vs. filter on CLP

- src/modules/icmaa-google-tag-manager/components/jsonld/Breadcrumbs.vue
- src/modules/icmaa-google-tag-manager/components/jsonld/JsonLdLoader.vue
- src/themes/icmaa-imp/components/core/Breadcrumbs.vue
> #250226 Add JSON-LD breadcrumbs

- src/modules/icmaa-google-tag-manager/components/jsonld/Breadcrumbs.vue
- src/modules/icmaa-google-tag-manager/components/jsonld/JsonLdLoader.vue
- src/themes/icmaa-imp/components/core/Breadcrumbs.vue
> #250226 Add JSON-LD breadcrumbs (#779)

- src/modules/icmaa-meta/mixins/categoryMeta.ts
* Use unified fields in category-response
> #250412 Improve category meta-titles and -descriptions (#785)

- src/themes/icmaa-imp/components/core/LanguageSwitcher.vue
- src/themes/icmaa-imp/components/core/blocks/Header/LanguageSwitcher.vue
- src/themes/icmaa-imp/components/core/blocks/Navigation/Sidebar.vue
- src/themes/icmaa-imp/components/core/blocks/Switcher/Language.vue
- src/themes/icmaa-imp/store/ui.ts
* This is a bugfix for the new delayed-modal feature and the language-modal of #792
TCK-250854
> Bugfix for delayed language-switcher

- src/modules/icmaa-google-tag-manager/components/jsonld/Product.vue
- src/themes/icmaa-imp/test/e2e/integration/Cms/home.spec.ts
* Also `htmlDecode` the description to prevent invalid JSON
TCK-252411
> #252411 Add GTIN to Google structured-data

- src/themes/icmaa-imp/test/e2e/integration/Checkout/paymentCreditcard.spec.ts
- src/themes/icmaa-imp/test/e2e/integration/Cms/home.spec.ts
- src/themes/icmaa-imp/test/e2e/support/commands.ts
> Bugfixes for flacky tests

- src/themes/icmaa-imp/components/core/blocks/CategoryExtras/Footer.vue
> Always show full description in PLP footer

- src/themes/icmaa-imp/resource/i18n/nl-NL.csv
> #254433 Add `Huisnummer` to Adress (Checkout NL) 

- src/themes/icmaa-imp/components/core/blocks/Microcart/Microcart.vue
> #248204 Remove PayPal-Express button from cart-sidebar

- core/scripts/server.h3.ts
* to prevent missing cache-tags and faulty requests in production
> Clear context after each request for `h3` server

- core/scripts/server.h3.ts
- src/themes/icmaa-imp/components/core/blocks/Microcart/Microcart.vue
- src/themes/icmaa-imp/components/core/blocks/SearchPanel/SearchPanel.vue
- src/themes/icmaa-imp/resource/i18n/nl-NL.csv
* #254433 Add house-number to adress-label in NL (#818)
* #248204 Remove PayPal-Express button from cart-sidebar (#819)
* #253983 Debounce GTM search-event (#820)   
* Clear context after each request for h3 server (#821)
> Release 2022-05-20

- src/themes/icmaa-imp/components/core/blocks/SearchPanel/SearchPanel.vue
> Track GTM search-results lowercase

- src/themes/icmaa-imp/components/core/blocks/ICMAA/Cms/Pages/ImpericonNeverSayDie.vue
> #255227 New color theme for INSD

- src/modules/robots/robots.txt
- src/themes/icmaa-imp/components/core/blocks/ICMAA/Cms/Pages/ImpericonNeverSayDie.vue
- src/themes/icmaa-imp/components/core/blocks/Reviews/ReviewsList.vue
- src/themes/icmaa-imp/pages/Product.vue
* #255227 New color theme for INSD (#831)
* #255640 Add sitemaps to robots.txt (#830)
* Bugfix for reviews on PDP (#832)
> Release 2022-06-10

- src/modules/icmaa-google-tag-manager/components/jsonld/JsonLdLoader.vue
- src/modules/icmaa-google-tag-manager/components/jsonld/Ticket.vue
- src/themes/icmaa-imp/pages/Product.vue
* There are some missing fields yet like `location.addressCountry` and `organizer`. Also multiple performers aren't considered yet
TCK-251677
> #251677 Add structured-data for tickets

- src/modules/icmaa-cms/mixins/Page.ts
> Add `cms` cache-tags to CMS pages

- src/themes/icmaa-imp/components/core/blocks/Reviews/ReviewsList.vue
> #255156 Remove obsolete Code in `ReviewsList`

- src/modules/icmaa-config/helpers/datetime.ts
- src/themes/icmaa-imp/components/core/blocks/SearchPanel/SearchPanel.vue
> #238147 Empty search-panel after 30 minutes

- src/modules/icmaa-category/components/List/List.vue
> #256691 Bugfix for A-Z navigation in mobile viewport

- src/modules/icmaa-config/helpers/datetime.ts
- src/modules/icmaa-paypal/components/Checkout/Button.vue
- src/modules/icmaa-paypal/components/Checkout/ButtonWrapper.vue
- src/themes/icmaa-imp/components/core/blocks/Auth/Login.vue
- src/themes/icmaa-imp/components/core/blocks/Checkout/PersonalDetails.vue
- src/themes/icmaa-imp/components/core/blocks/SearchPanel/SearchPanel.vue
- src/themes/icmaa-imp/tailwind.js
* We hide several UX elements for the login until they're needed
* We also rearranged some buttons and changed the color of the PP Express button
TCK-248203
> #248203 Improve UX for login in checkout

- src/themes/icmaa-imp/components/core/ProductImage.vue
- src/themes/icmaa-imp/components/core/blocks/Product/ProductGallery.vue
- src/themes/icmaa-imp/router/icmaa-cms/index.ts
> #257102 Improve image-size on PDP

- src/themes/icmaa-imp/test/e2e/integration/Menu/footer.spec.ts
> Update `Menu/footer.spec.ts` acceptance test

- src/themes/icmaa-imp/pages/Home.vue
> #260401 Switch elements on homepage

- src/modules/icmaa-cms/components/Block.vue
- src/modules/icmaa-cms/components/Wrapper.vue
- src/modules/icmaa-cms/helpers/index.ts
- src/themes/icmaa-imp/components/core/blocks/RichText.vue
> #258705 improve rte rendering

- core/data-resolver/types/DataResolver.d.ts
- core/modules/catalog-next/store/category/actions.ts
- core/modules/catalog-next/store/category/mutations.ts
- src/modules/icmaa-catalog/store/category/actions.ts
- src/modules/icmaa-category-extras/store/getters.ts
- src/modules/icmaa-user/mixins/cluster.ts
- src/modules/icmaa-user/store/actions/user-session.ts
- src/themes/icmaa-imp/components/core/blocks/CategoryExtras/DepartmentLogo.vue
- src/themes/icmaa-imp/components/core/blocks/CategoryExtras/Header.vue
- src/themes/icmaa-imp/components/core/blocks/CategoryExtras/LogoLine.vue
- src/themes/icmaa-imp/pages/Product.vue
- src/themes/icmaa-imp/resource/i18n/de-DE.csv
* Related to https://github.com/icmaa/shop-workspace/commit/6fb5d0642f1cc170904ff637df3cb2b6c6b2c044
TCK-260458
> #260458 Add logoline to fashion categories and products

- src/themes/icmaa-imp/components/core/blocks/CategoryExtras/Footer.vue
> #258705 Render deprecated footer as component (migration-mode)

- src/themes/icmaa-imp/webpack.config.js
> #258705 Add `lg:t-float-right` to TailwindCSS allowlist

- src/modules/icmaa-cms/components/Wrapper.vue
- src/modules/icmaa-cms/helpers/index.ts
> #258705 Don't render external images with picture-component and improve styling

- src/modules/icmaa-cms/components/Wrapper.vue
- src/modules/icmaa-cms/helpers/index.ts
- src/modules/icmaa-competitions/pages/Competition.vue
* #258705 Don't render external images with picture-component and improve styling (#866)
* #263116 Add success content to competitions (#867)
> Release 2022-09-28

- src/themes/icmaa-imp/components/core/blocks/Reviews/ReviewsStars.vue
> Bugfix for review-star styling on PDP

- src/themes/icmaa-imp/components/core/blocks/Checkout/PersonalDetails.vue
* **Note:** we don't disable it, just hide the button. This PR needs to be reverted when the current problems are maintained
TCK-263774
> #263774 Hide PayPal's checkout button until the bugfix

- src/themes/icmaa-imp/mixins/product/featuresMixin.ts
> #264242 Move attribute `features_accessories` to the features tab

- src/modules/icmaa-meta/mixins/categoryMeta.ts
- src/modules/icmaa-meta/mixins/productMeta.ts
- src/themes/icmaa-imp/components/core/blocks/CategoryExtras/Header.vue
- src/themes/icmaa-imp/components/core/blocks/Picture.vue
- src/themes/icmaa-imp/mixins/product/featuresMixin.ts
* #265822 & #265975 SEO optimizations (#881) 
* #265975 Add `meta_description` to meta-tags
* #265822 Add category-header to as `<link rel="preload" />` tag 
* #264242 Move attribute features_accessories to the features tab (#882)
> Release 2022-11-21

- .github/workflows/build-sc.yml
- docker/scale-commerce/Dockerfile
> #266589 Create build-job for ScaleCommerce deployment

- src/themes/icmaa-imp/components/core/blocks/CategoryExtras/LogoLine.vue
> #267374 Hide subcategories in logoline of landing-pages

- docker/scale-commerce/Dockerfile
> #266589 Add default env-vars to SC docker image

- src/modules/icmaa-config/helpers/datetime.ts
> #269961 Add check for a valid year into date validator

- core/i18n/resource/i18n/de-DE.csv
- core/i18n/resource/i18n/en-US.csv
- src/modules/icmaa-tracking/README.md
- src/modules/icmaa-tracking/components/TrackingLink.vue
- src/modules/icmaa-tracking/index.ts
- src/modules/icmaa-tracking/pages/Tracking.vue
- src/modules/icmaa-tracking/routes.ts
* #268886 Add Paqato tracking to customer-account and add custom `/order-tracking` route
> Release 2023-02-10

- src/modules/icmaa-google-tag-manager/hooks/afterRegistration.ts
- src/modules/icmaa-google-tag-manager/hooks/index.ts
- src/modules/icmaa-google-tag-manager/index.ts
- src/themes/icmaa-imp/pages/Home.vue
- src/themes/icmaa-imp/pages/PageNotFound.vue
- src/themes/icmaa-imp/router/index.ts
* Connected to https://github.com/icmaa/shop-workspace/pull/74
TCK-275506
> #275506 Add new data-layer-event for home-page visit

- docker/vue-storefront/Dockerfile
> Add `gh` GitHub CLI tool to `devcontainer`

- src/modules/icmaa-checkout/pages/Checkout.ts
> #277512 Bugfix for possible string-injection in checkout

- src/modules/icmaa-user/index.ts
- src/themes/icmaa-imp/pages/Home.vue
> #275958 Bugfix for account redirect-paths /w parameters

- src/modules/icmaa-teaser/store/actions.ts
> Update name of Storyblok datasource for `teaser-tags`

- src/modules/icmaa-google-tag-manager/store/index.ts
> #275144 Add `m_id`and `id as sku` to the children-node

- src/modules/icmaa-catalog/components/Product.ts
- src/modules/icmaa-category-extras/store/getters.ts
- src/modules/icmaa-meta/mixins/productMeta.ts
> #277755 Add `entertainment` as account-department

- src/themes/icmaa-imp/components/core/blocks/WebShare.vue
> Bugfix for missing URL in webshare-buttons on SSR

- core/modules/order/components/UserSingleOrder.ts
- core/scripts/generate-files.ts
- src/themes/icmaa-imp/components/core/blocks/MyAccount/MyOrder.vue
- tsconfig.json
* #279501 Bugfix for configurable options on `/my-account/orders` page
* Change path of theme in `tsconfig.json`
TCK-279501
> #279501 Bugfix for configurable options on `/my-account/orders` page

- .github/workflows/build-sc.yml
> #266589 Trigger ScaleCommerce GitLab pipeline after Docker image-build

- src/themes/icmaa-imp/pages/Category.vue
> #282012 Increase product-count on CLP to 24

- src/themes/icmaa-imp/pages/Category.vue
This reverts commit 591763178f2961e6cb55875cce71666510f1c3ea (#935).
TCK-282012
> Revert "#282012 Increase product-count on CLP to 24"

- src/themes/icmaa-imp/components/core/blocks/CategoryExtras/Footer.vue
- src/themes/icmaa-imp/pages/Category.vue
> #286051 Optimized `h1` on CLP

- src/themes/icmaa-imp/components/core/blocks/CategoryExtras/Footer.vue
- src/themes/icmaa-imp/pages/Category.vue
* #286051 Optimized `h1` on CLP (#945)
> Release 2023-09-18

- src/modules/icmaa-recommendations/store/getters.ts
> #275142 Use correct GA id for recommendations

- src/modules/icmaa-cms/components/Storyblok/NewsletterSubscription.vue
- src/modules/icmaa-cms/components/Wrapper.vue
- src/modules/icmaa-newsletter/pages/Newsletter.vue
- src/themes/icmaa-imp/components/core/blocks/Footer/Footer.vue
- src/themes/icmaa-imp/components/core/blocks/Footer/Newsletter.vue
> #288858 Add newsletter-subscription CMS block

- src/modules/icmaa-blog/components/List.vue
- src/modules/icmaa-blog/components/ListCategoryHeadline.vue
- src/modules/icmaa-category/components/ProductListingWidget.vue
- src/modules/icmaa-cms/components/Storyblok/ImageTabs.vue
- src/modules/icmaa-cms/components/Storyblok/NewsletterSubscription.vue
- src/modules/icmaa-cms/components/Storyblok/YouTube.vue
- src/modules/icmaa-cms/components/Wrapper.vue
- src/modules/icmaa-newsletter/pages/Newsletter.vue
- src/themes/icmaa-imp/components/core/ProductListingTicket.vue
- src/themes/icmaa-imp/components/core/blocks/Footer/Footer.vue
- src/themes/icmaa-imp/components/core/blocks/Footer/Newsletter.vue
- src/themes/icmaa-imp/components/core/blocks/Picture.vue
- src/themes/icmaa-imp/pages/Category.vue
* #278156 Improve icmaa-blog headlines (#950)
* #287061 Add new Components for Festival Landingpage (#951) 
* #288858 Add newsletter-subscription CMS block (#953)
> Release 2023-10-13

- src/themes/icmaa-imp/resource/i18n/sv-SE.csv
… Short description of your changes with links to related PR's of other repos.
TCK-290362
> #290362 Fix l10n 

- src/themes/icmaa-imp/components/core/blocks/Product/ProductFeatures.vue
> #290074 Remove feature-attribute label on PDP

- src/themes/icmaa-imp/pages/Cms/ImpericonNeverSayDie.vue
> #292513 Change color theme for `INSD` Page

- src/themes/icmaa-imp/pages/Cms/ImpericonNeverSayDie.vue
* #292513 Change color theme for `INSD` Page (#963)
> Release 2023-12-14

- src/modules/icmaa-meta/mixins/categoryMeta.ts
* #302646 Remove pagination param from canonical URL on CLP (#967)
> Release 2024-03-28
